# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 FlyDSL Project Contributors

"""Generate HIP C header + .o for AOT-compiled FlyDSL kernels.

- export_to_c() produces .h + .o
- User links .o into .so themselves (gcc -shared) for multi-kernel libraries
- load_module() handles .o → .so linking automatically at load time
"""

import os
from typing import TYPE_CHECKING

from .object_export import dump_to_object

if TYPE_CHECKING:
    from ..jit_executor import CompiledArtifact


_HEADER_TEMPLATE = """\
/* Auto-generated by FlyDSL AOT export.
 * Target arch: {arch}
 * FlyDSL version: {version}
 *
 * GPU module loading:
 *   The .o contains ELF global constructors that automatically call
 *   hipModuleLoadData when the shared library is loaded (dlopen).
 *   No explicit init/fini calls are needed.
 *
 * Link with:
 *   gcc -shared -o lib{file_name}.so {file_name}.o \\
 *       -L<flydsl_mlir_libs_dir> -lfly_jit_runtime -lmlir_c_runner_utils \\
 *       -Wl,-rpath,<flydsl_mlir_libs_dir>
 */
#pragma once

#include <hip/hip_runtime.h>
#include <stdio.h>
#include <stdint.h>

#define FLYDSL_HIP_CHECK(err) do {{ \\
    if ((err) != hipSuccess) {{ \\
        fprintf(stderr, "FlyDSL HIP error: %s at %s:%d\\n", \\
                hipGetErrorString(err), __FILE__, __LINE__); \\
    }} \\
}} while(0)

#ifdef __cplusplus
extern "C" {{
#endif

/* Host wrapper entry point (generated by MLIR llvm.emit_c_interface).
 * packed_args is a void** array of pointers to each argument. */
extern void _mlir_{ciface_name}(void *packed_args);

/* Convenience launch wrapper. */
static inline void {prefix}_launch(void *packed_args) {{
    _mlir_{ciface_name}(packed_args);
}}

/* Metadata (null-terminated strings embedded in the .o file). */
extern const char {prefix}_entry_name[];
extern const char {prefix}_fly_version[];
extern const char {prefix}_gpu_arch[];

#ifdef __cplusplus
}}
#endif
"""


def export_to_c(
    artifact: "CompiledArtifact",
    file_path: str,
    file_name: str,
    function_prefix: str,
    arch: str = "",
) -> None:
    """Export a compiled kernel as C header + object file.

    Produces two files:
      ``{file_name}.h``  — C header with launch wrapper and metadata decls
      ``{file_name}.o``  — Relocatable ELF object (host wrapper + GPU binary)

    To link into a shared library (single or multi-kernel):
      ``gcc -shared -o lib{file_name}.so {file_name}.o -lfly_jit_runtime -lmlir_c_runner_utils``

    To load in Python:
      ``mod = load_module("{file_name}.o")``  # links .o → .so automatically
    """
    if not arch:
        from ...runtime.device import get_rocm_arch
        try:
            arch = get_rocm_arch()
        except Exception:
            arch = "unknown"

    import flydsl

    os.makedirs(file_path, exist_ok=True)

    ciface_name = f"{function_prefix}_{artifact._entry}"

    # .h
    header_content = _HEADER_TEMPLATE.format(
        arch=arch,
        version=flydsl.__version__,
        file_name=file_name,
        prefix=function_prefix,
        ciface_name=ciface_name,
    )
    with open(os.path.join(file_path, f"{file_name}.h"), "w") as f:
        f.write(header_content)

    # .o
    obj_bytes = dump_to_object(artifact, function_prefix, arch=arch)
    with open(os.path.join(file_path, f"{file_name}.o"), "wb") as f:
        f.write(obj_bytes)
