#ifndef CONVERSION_FLYGPUSTREAMINJECT_FLYGPUSTREAMINJECT_H
#define CONVERSION_FLYGPUSTREAMINJECT_FLYGPUSTREAMINJECT_H

#include "mlir/Pass/Pass.h"

namespace mlir {
#define GEN_PASS_DECL_FLYGPUSTREAMMARKPASS
#define GEN_PASS_DECL_FLYGPUSTREAMINJECTPASS
#include "flydsl/Conversion/Passes.h.inc"
} // namespace mlir

#endif // CONVERSION_FLYGPUSTREAMINJECT_FLYGPUSTREAMINJECT_H
