"""
FlyDSL kernel generated from Fly MLIR
Target: hip:gfx1250
Warps: 4, Threads/Warp: 32

Generated by triton.tools.fly_to_flydsl
"""

import math
import flydsl.expr as fx
import flydsl.compiler as flyc
from flydsl.expr import arith, vector, gpu, rocdl, buffer_ops
from flydsl.expr.rocdl import tdm_ops
from flydsl.expr.typing import T
from flydsl._mlir.dialects import math as math_dialect
from flydsl._mlir import ir
from flydsl._mlir.dialects import llvm as llvm_dialect
from flydsl._mlir.dialects import arith as std_arith
from flydsl._mlir.dialects import memref as memref_dialect
from flydsl._mlir.dialects import fly as _fly_d
from flydsl.expr.utils.arith import ArithValue as _ArithValue
from flydsl._mlir.dialects import scf as _scf_dialect
from flydsl.utils.smem_allocator import SmemAllocator, SmemPtr
from flydsl.compiler.jit_function import CompilationContext

NUM_WARPS = 4
THREADS_PER_WARP = 32
TARGET = "hip:gfx1250"

def _addptr(base, offset, elem_bytes=2):
    """Triton-style pointer arithmetic: base + offset * elem_bytes.

    If base is a memref, extracts the raw LLVM pointer first.
    Returns an i64 byte address.
    """
    i64 = ir.IntegerType.get_signless(64)
    i32 = ir.IntegerType.get_signless(32)
    # Extract raw pointer from memref if needed
    base_val = base
    if hasattr(base, "type") and "memref" in str(base.type):
        glb_ptr_type = ir.Type.parse("!llvm.ptr<1>")
        base_ptr = _fly_d.extract_aligned_pointer_as_index(glb_ptr_type, base)
        base_val = _ArithValue(llvm_dialect.ptrtoint(i64, base_ptr))
    elif hasattr(base, "type") and str(base.type) == "i64":
        base_val = _ArithValue(base)
    else:
        # Already an i64 byte address
        base_val = _ArithValue(base) if not isinstance(base, _ArithValue) else base
    # Convert offset to i64 byte offset
    offset_val = offset
    if hasattr(offset, "type") and str(offset.type) == "i32":
        offset_val = std_arith.ExtSIOp(i64, offset).result
    elem_bytes_val = std_arith.ConstantOp(i64, ir.IntegerAttr.get(i64, elem_bytes)).result
    byte_offset = _ArithValue(std_arith.MulIOp(offset_val, elem_bytes_val).result)
    return _ArithValue(std_arith.AddIOp(base_val, byte_offset).result)


def _make_tdm_desc(base_addr_i64, shapes, strides, elem_bytes=2, tile_shape=None, num_warps=1):
    """Construct a TDM descriptor from a raw i64 byte address + shapes + strides.

    tile_shape: (outer_tile, inner_tile) static tile dimensions for the TDM descriptor.
    num_warps: number of warps in the workgroup (for per-warp distribution).
    Returns a TDMDescriptor2D (dgroup0, dgroup1) with per-warp metadata.
    """
    i32 = ir.IntegerType.get_signless(32)
    i64 = ir.IntegerType.get_signless(64)

    from flydsl.expr import rocdl as _rocdl_ext
    from flydsl.expr.rocdl.tdm_ops import compute_warp_distribution
    outer_stride = strides[0]

    # Tile shape
    if tile_shape is not None:
        _tile_outer, _tile_inner = tile_shape
    else:
        _tile_outer = _tile_inner = 128

    # Per-warp distribution (matches tdm_ops.make_tensor_descriptor_2d)
    _warps_per_dim, _block_per_warp = compute_warp_distribution(
        [_tile_outer, _tile_inner], num_warps)
    bpw_outer, bpw_inner = _block_per_warp
    warps_dim0 = _warps_per_dim[0]

    # Get base address
    glb_addr_i64 = _ArithValue(base_addr_i64)

    # Per-warp global address offset via wave_id
    if num_warps > 1:
        _wid_i32 = _rocdl_ext.wave_id()
        _wid_idx = arith.index_cast(T.index, _wid_i32)
        _warp_coord_outer = _wid_idx % arith.index(warps_dim0)
        _warp_coord_inner = _wid_idx / arith.index(warps_dim0)
        _warp_off_outer = _warp_coord_outer * arith.index(bpw_outer)
        _warp_off_inner = _warp_coord_inner * arith.index(bpw_inner)
        # Global byte offset: (warp_off_outer * outer_stride + warp_off_inner) * elem_bytes
        if hasattr(outer_stride, "type") and str(outer_stride.type) == "i64":
            _stride_idx = arith.index_cast(T.index, std_arith.TruncIOp(i32, outer_stride).result)
        elif hasattr(outer_stride, "type") and str(outer_stride.type) == "i32":
            _stride_idx = arith.index_cast(T.index, outer_stride)
        else:
            _stride_idx = arith.index(int(outer_stride) if not hasattr(outer_stride, "type") else 1)
        _warp_elem_off = _warp_off_outer * _stride_idx + _warp_off_inner
        _warp_byte_off = _warp_elem_off * arith.index(elem_bytes)
        _warp_byte_off_i64 = arith.index_cast(T.i64, _warp_byte_off)
        glb_addr_i64 = _ArithValue(std_arith.AddIOp(glb_addr_i64, _warp_byte_off_i64).result)

    # LDS address placeholder (will be filled by tdm_copy)
    lds_addr_i32 = arith.constant(0, type=T.i32)

    # GROUP0: pred, lds_addr, global_addr_lo/hi
    g0_s0 = arith.constant(1, type=T.i32)  # pred = enabled
    g0_s1 = lds_addr_i32
    g0_s2 = _ArithValue(std_arith.TruncIOp(i32, glb_addr_i64).result)
    hi_raw = _ArithValue(glb_addr_i64).shrui(arith.constant(32, type=T.i64))
    g0_s3 = _ArithValue(std_arith.TruncIOp(i32, hi_raw).result) | arith.constant(1 << 31, type=T.i32)
    dgroup0 = vector.from_elements(T.vec(4, T.i32), [g0_s0, g0_s1, g0_s2, g0_s3])

    # GROUP1: config + tensor dims + tile (using per-warp dims)
    data_size_code = int(math.log2(elem_bytes))
    g1_s0_upper = (data_size_code << 16)
    g1_s0 = arith.constant(g1_s0_upper, type=T.i32)
    # Per-warp dims: dim0=innermost=bpw_inner, dim1=outermost=bpw_outer
    # Matches tdm_ops.make_tensor_descriptor_2d encoding
    g1_s1 = arith.constant((bpw_inner & 0xFFFF) << 16, type=T.i32)   # tdim0_lo
    g1_s2 = arith.constant((bpw_outer & 0xFFFF) << 16, type=T.i32)   # tdim1_lo
    g1_s3 = arith.constant(bpw_inner << 16, type=T.i32)               # tile_d0
    g1_s4 = arith.constant(bpw_outer & 0xFFFF, type=T.i32)            # tile_d1
    # stride (outer stride in elements)
    if hasattr(outer_stride, "type") and str(outer_stride.type) == "i64":
        g1_s5 = _ArithValue(std_arith.TruncIOp(i32, outer_stride).result)
    else:
        g1_s5 = outer_stride
    g1_s6 = arith.constant(0, type=T.i32)
    g1_s7 = arith.constant(0, type=T.i32)
    dgroup1 = vector.from_elements(
        T.vec(8, T.i32), [g1_s0, g1_s1, g1_s2, g1_s3, g1_s4, g1_s5, g1_s6, g1_s7])

    desc = tdm_ops.TDMDescriptor2D(dgroup0=dgroup0, dgroup1=dgroup1)
    # Store per-warp metadata for _tdm_copy_to_lds
    desc._bpw_outer = bpw_outer
    desc._bpw_inner = bpw_inner
    desc._warps_dim0 = warps_dim0
    desc._tile_inner = _tile_inner
    desc._num_warps = num_warps
    return desc


# _lds_alloc removed — LDS allocation now uses SmemAllocator/SmemPtr


def _tdm_copy_to_lds(desc, offsets, dst, elem_bytes=2):
    """TDM async copy from global to LDS.

    Creates an updated descriptor with:
    1. LDS target address from dst memref (with per-warp offset)
    2. Global source address offset by (outer_off * stride + inner_off)
    Then issues the async copy.
    """
    from flydsl._mlir.dialects import vector as _vec_d
    i32 = ir.IntegerType.get_signless(32)
    i64 = ir.IntegerType.get_signless(64)

    # Get LDS byte address from dst memref
    lds_base_idx = memref_dialect.extract_aligned_pointer_as_index(dst)

    # Add per-warp LDS offset
    _nw = getattr(desc, "_num_warps", 1)
    if _nw > 1:
        from flydsl.expr import rocdl as _rocdl_ext
        _wid = arith.index_cast(T.index, _rocdl_ext.wave_id())
        _wco = _wid % arith.index(desc._warps_dim0)
        _wci = _wid / arith.index(desc._warps_dim0)
        _woo = _wco * arith.index(desc._bpw_outer)
        _woi = _wci * arith.index(desc._bpw_inner)
        # LDS inner stride = tile_inner (no padding in current codegen)
        _lds_warp_elem = _woo * arith.index(desc._tile_inner) + _woi
        _lds_warp_bytes = _lds_warp_elem * arith.index(elem_bytes)
        lds_base_idx = std_arith.AddIOp(lds_base_idx,
            std_arith.IndexCastOp(ir.IndexType.get(), _lds_warp_bytes).result
            if not hasattr(_lds_warp_bytes, "type") or str(getattr(_lds_warp_bytes, "type", "")) != "index"
            else _lds_warp_bytes).result

    lds_addr_i32 = std_arith.IndexCastOp(i32, lds_base_idx).result

    # Build updated dgroup0 with correct LDS address
    g0_s0 = _vec_d.extract(desc.dgroup0, [], [0])
    g0_s1 = lds_addr_i32  # LDS target address (includes per-warp offset)

    # Apply outer + inner offsets to global address
    # offsets = (outer_off, inner_off)
    outer_off_raw = offsets[0]
    if hasattr(outer_off_raw, "type") and str(outer_off_raw.type) == "i32":
        outer_off_i64 = std_arith.ExtSIOp(i64, outer_off_raw).result
    elif hasattr(outer_off_raw, "type") and str(outer_off_raw.type) == "i64":
        outer_off_i64 = outer_off_raw
    else:
        outer_off_i64 = std_arith.ExtSIOp(i64, outer_off_raw).result

    # Extract original global addr from dgroup0[2:3]
    orig_lo = _vec_d.extract(desc.dgroup0, [], [2])
    orig_hi = _vec_d.extract(desc.dgroup0, [], [3])
    # Reconstruct i64 global addr
    lo_i64 = std_arith.ExtUIOp(i64, orig_lo).result
    hi_masked = std_arith.AndIOp(orig_hi, std_arith.ConstantOp(i32, ir.IntegerAttr.get(i32, 0x7FFFFFFF)).result).result
    hi_i64 = std_arith.ExtUIOp(i64, hi_masked).result
    shift_32 = std_arith.ConstantOp(i64, ir.IntegerAttr.get(i64, 32)).result
    hi_shifted = std_arith.ShLIOp(hi_i64, shift_32).result
    orig_addr = std_arith.AddIOp(lo_i64, hi_shifted).result

    # Extract stride from dgroup1[5] (outer stride in elements)
    stride_i32 = _vec_d.extract(desc.dgroup1, [], [5])
    stride_i64 = std_arith.ExtSIOp(i64, stride_i32).result

    # off_bytes = (outer_off * stride + inner_off) * elem_bytes
    # inner_stride is always 1 for TDM descriptors (contiguous innermost)
    off_elems = std_arith.MulIOp(outer_off_i64, stride_i64).result
    # Add inner offset if present
    if len(offsets) > 1:
        inner_off_raw = offsets[1]
        if hasattr(inner_off_raw, "type") and str(inner_off_raw.type) == "i32":
            inner_off_i64 = std_arith.ExtSIOp(i64, inner_off_raw).result
        elif hasattr(inner_off_raw, "type") and str(inner_off_raw.type) == "i64":
            inner_off_i64 = inner_off_raw
        else:
            inner_off_i64 = std_arith.ExtSIOp(i64, inner_off_raw).result
        off_elems = std_arith.AddIOp(off_elems, inner_off_i64).result
    eb = std_arith.ConstantOp(i64, ir.IntegerAttr.get(i64, elem_bytes)).result
    off_bytes = std_arith.MulIOp(off_elems, eb).result
    new_addr = std_arith.AddIOp(orig_addr, off_bytes).result

    # Split new addr to lo/hi
    g0_s2 = std_arith.TruncIOp(i32, new_addr).result
    hi_raw = std_arith.ShRUIOp(new_addr, shift_32).result
    hi_trunc = std_arith.TruncIOp(i32, hi_raw).result
    type_bit = std_arith.ConstantOp(i32, ir.IntegerAttr.get(i32, 1 << 31)).result
    g0_s3 = std_arith.OrIOp(hi_trunc, type_bit).result

    new_dg0 = vector.from_elements(T.vec(4, T.i32), [g0_s0, g0_s1, g0_s2, g0_s3])

    updated_desc = tdm_ops.TDMDescriptor2D(dgroup0=new_dg0, dgroup1=desc.dgroup1)
    tdm_ops.tensor_load_2d(updated_desc)
    return dst


def _to_index(val):
    """Convert a value to MLIR index type."""
    if isinstance(val, ir.Value):
        if val.type == ir.IndexType.get():
            return val
        return std_arith.IndexCastOp(ir.IndexType.get(), val).result
    if hasattr(val, "ir_value"):
        raw = val.ir_value()
        if isinstance(raw, ir.Value) and raw.type != ir.IndexType.get():
            return std_arith.IndexCastOp(ir.IndexType.get(), raw).result
        return raw
    if isinstance(val, int):
        return std_arith.ConstantOp(ir.IndexType.get(), val).result
    raise TypeError(f"_to_index: unexpected type {type(val)}")


class _SCFForCtx:
    """Context manager for scf.for loop."""
    def __init__(self, lb, ub, step, init_vals=None):
        start = _to_index(lb)
        stop = _to_index(ub)
        step_v = _to_index(step)
        raw_inits = []
        if init_vals:
            for v in init_vals:
                if isinstance(v, ir.Value):
                    raw_inits.append(v)
                elif hasattr(v, "ir_value"):
                    raw_inits.append(v.ir_value())
                else:
                    raw_inits.append(v)
        if raw_inits:
            self.for_op = _scf_dialect.ForOp(start, stop, step_v, raw_inits)
        else:
            self.for_op = _scf_dialect.ForOp(start, stop, step_v)
        self.ip = ir.InsertionPoint(self.for_op.body)

    def __enter__(self):
        self.ip.__enter__()
        iv = self.for_op.induction_variable
        iargs = list(self.for_op.inner_iter_args) if self.for_op.inner_iter_args else []
        return iv, iargs

    def __exit__(self, *args):
        self.ip.__exit__(*args)

    @property
    def results(self):
        return list(self.for_op.results)


def _scf_yield_(vals):
    """Emit scf.yield with the given values."""
    raw = []
    for v in vals:
        if isinstance(v, ir.Value):
            raw.append(v)
        elif hasattr(v, "ir_value"):
            raw.append(v.ir_value())
        else:
            raw.append(v)
    _scf_dialect.YieldOp(raw)


def _wmma_gemm_full(a_data, b_lds_ref, c_vec, ab_dtype,
                     tile_m=128, tile_n=128, tile_k=128,
                     warps_m=4, warps_n=1, WMMA_M=16, WMMA_N=16, WMMA_K=32):
    """Complete tiled WMMA gemm: A (register vec) × B (LDS memref) → C (f32 vec).

    A is a flat per-thread register vector from buffer_load (dot_op opIdx=0 layout).
    B is a LDS memref from TDM copy, loaded with WMMA-aware per-element addressing.
    C is the per-thread accumulator vector (f32).

    warps_m/warps_n: how many warps split the M/N dimensions.
    For FA kernel: warps_m=4, warps_n=1 (4 warps along M, each does all N).

    Thread decomposition: lane16 = tid % 16, lane_kgrp = (tid // 16) % 2.
    A fragment: 16 consecutive elements from flat vec.
    B fragment: 16 elements loaded from LDS with WMMA addressing.
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    from flydsl._mlir.dialects import memref as _mr_d
    from flydsl.expr import rocdl

    raw_ab = ab_dtype
    if hasattr(raw_ab, "ir_type"):
        raw_ab = raw_ab.ir_type()
    is_bf16 = str(raw_ab) == "bf16"
    wmma_op = rocdl.wmma_f32_16x16x32_bf16 if is_bf16 else rocdl.wmma_f32_16x16x32_f16
    elem_ty = raw_ab

    # Unwrap values
    a_v = a_data.ir_value() if hasattr(a_data, "ir_value") else a_data
    c_v = c_vec.ir_value() if hasattr(c_vec, "ir_value") else c_vec

    # Check if a_data is a flat register vector (VectorType) vs LDS memref (MemRefType).
    # Both VectorType and MemRefType have .shape/.element_type, so use isinstance.
    a_is_vec = isinstance(a_v.type, ir.VectorType)

    # ── CuTE layout definitions ──
    # Thread layout: (warps_m, warps_n, kgrp=2, lane=16)
    #   tid → (wave_m_idx, wave_n_idx, lane_kgrp, lane16)
    layout_thr = fx.make_layout(
        (warps_m, warps_n, 2, 16),
        (warps_n * 32, 32, 16, 1))

    # Thread decomposition via CuTE idx2crd
    tid_raw = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, tid_raw)
    thr_crd = _idx2crd(tid, layout_thr)
    wave_m_idx = fx.get(thr_crd, 0)
    wave_n_idx = fx.get(thr_crd, 1)
    lane_kgrp  = fx.get(thr_crd, 2)
    lane16     = fx.get(thr_crd, 3)

    warp_tile_m = tile_m // warps_m
    warp_tile_n = tile_n // warps_n
    wmma_m_rep = warp_tile_m // WMMA_M
    wmma_n_rep = warp_tile_n // WMMA_N
    k_wmma_steps = tile_k // WMMA_K
    n_accs = wmma_m_rep * wmma_n_rep

    # Warp-level M and N base offsets
    warp_m_off = wave_m_idx * arith.index(warp_tile_m)
    warp_n_off = wave_n_idx * arith.index(warp_tile_n)

    # Initialize accumulators from c_vec (8 f32 per WMMA result)
    c_per_wmma = 8
    wmma_result_type = ir.VectorType.get([c_per_wmma], ir.F32Type.get())
    accs = []
    for i in range(n_accs):
        c_slice_list = []
        for j in range(c_per_wmma):
            c_slice_list.append(_vec_dialect.extract(c_v, [], [i * c_per_wmma + j]))
        c_slice = vector.from_elements(wmma_result_type, c_slice_list)
        accs.append(c_slice)

    # Get LDS memref for B operand
    # b_lds_ref may be a (memref, transposed=True) tuple from memdesc_trans
    b_transposed = False
    if isinstance(b_lds_ref, tuple):
        b_lds_flat, b_transposed = b_lds_ref
    else:
        b_lds_flat = b_lds_ref

    a_frag_type = ir.VectorType.get([16], elem_ty)
    b_frag_type = ir.VectorType.get([16], elem_ty)

    # LDS layouts for crd2idx-based offset computation
    if b_transposed:
        # B stored as B^T[n, k] row-major: layout (tile_n, tile_k):(tile_k, 1)
        layout_lds_b = fx.make_layout((tile_n, tile_k), (tile_k, 1))
    else:
        # B stored row-major B[k, n]: layout (tile_k, tile_n):(tile_n, 1)
        layout_lds_b = fx.make_layout((tile_k, tile_n), (tile_n, 1))
    layout_lds_a = fx.make_layout((tile_m, tile_k), (tile_k, 1))

    for ks in range(k_wmma_steps):
        k_step = arith.index(ks * WMMA_K)

        # Load B fragments from LDS for each N-tile in this warp
        b_frags = []
        for wn in range(wmma_n_rep):
            n_off = warp_n_off + arith.index(wn * WMMA_N)
            vals = []
            for k0 in range(2):
                for k1 in range(8):
                    kk = k_step + (arith.index(k0 * 2) + lane_kgrp) * arith.index(8) + arith.index(k1)
                    if b_transposed:
                        off = _crd2idx((n_off + lane16, kk), layout_lds_b)
                    else:
                        off = _crd2idx((kk, n_off + lane16), layout_lds_b)
                    val = _mr_d.load(b_lds_flat, [off])
                    vals.append(val)
            b_frags.append(vector.from_elements(b_frag_type, vals))

        # For each M-tile, extract A fragment and call WMMA
        for wm in range(wmma_m_rep):
            if a_is_vec:
                # A is in flat register vector (dot_op opIdx=0 layout)
                # Register layout: [m_tile_local * (k_wmma_steps * 16) + ks * 16 + 0..15]
                a_start = wm * (k_wmma_steps * 16) + ks * 16
                a_vals = []
                for j in range(16):
                    a_vals.append(_vec_dialect.extract(a_v, [], [a_start + j]))
                a_frag = vector.from_elements(a_frag_type, a_vals)
            else:
                # A is also in LDS — use crd2idx with warp M offset
                a_vals = []
                m_off = warp_m_off + arith.index(wm * WMMA_M)
                for k0 in range(2):
                    for k1 in range(8):
                        kk = k_step + (arith.index(k0 * 2) + lane_kgrp) * arith.index(8) + arith.index(k1)
                        off = _crd2idx((m_off + lane16, kk), layout_lds_a)
                        a_vals.append(_mr_d.load(a_data, [off]))
                a_frag = vector.from_elements(a_frag_type, a_vals)

            for wn in range(wmma_n_rep):
                acc_idx = wm * wmma_n_rep + wn
                accs[acc_idx] = wmma_op(
                    wmma_result_type,
                    b_frags[wn],
                    a_frag,
                    accs[acc_idx],
                    signA=False, signB=False, modC=0,
                    reuseA=False, reuseB=False,
                ).result

    # Pack accumulators back into a flat result vector
    result = c_v
    for i in range(n_accs):
        for j in range(c_per_wmma):
            elem = _vec_dialect.extract(accs[i], [], [j])
            result = _vec_dialect.insert(elem, result, [], [i * c_per_wmma + j])

    return result


def _crd2idx(crd, layout):
    """CuTE crd2idx: (coord, layout) → index-typed scalar offset."""
    result = fx.crd2idx(crd, layout)
    scalar = fx.get_scalar(result)
    if isinstance(scalar, ir.Value) and not isinstance(scalar.type, ir.IndexType):
        scalar = std_arith.IndexCastOp(ir.IndexType.get(), scalar).result
    return scalar


def _idx2crd(idx, layout):
    """CuTE idx2crd: (linear_index, layout) → coordinate tuple.

    Returns the raw fly.int_tuple; use fx.get(result, i) to extract mode i.
    """
    if isinstance(idx, ir.Value) and not str(idx.type).startswith("!fly.int_tuple"):
        idx_i32 = idx
        if str(idx.type) != "i32":
            idx_i32 = std_arith.IndexCastOp(ir.IntegerType.get_signless(32), idx).result
        IntTupleTy, dyncElems = _fly_d.infer_int_tuple_type(idx_i32)
        idx = _fly_d.make_int_tuple(IntTupleTy, dyncElems)
    return fx.idx2crd(idx, layout)


def _buffer_load_dot_op_a(memref_ptr, offsets, masks, n_elems, elem_dtype,
                           tile_m=128, tile_k=128, warps_m=4, warps_n=1,
                           stride_m=128, WMMA_M=16, WMMA_N=16, WMMA_K=32):
    """Load A operand (Q) from global memory with dot_op opIdx=0 layout.

    The Triton dot_op<opIdx=0> encoding distributes the 128x128 A tile
    across threads according to the WMMA A-operand layout.
    Each thread loads 128 elements covering specific (M, K) positions.

    offsets is a per-element vector pre-computed by the MLIR lowering:
      offsets[flat_idx] = batch_head_off + M(flat_idx) * stride_m + K(flat_idx)
    where M and K follow the WMMA A-input linear layout (wm*64 + wave_id*16 + lane16).
    We use offsets[flat_idx] directly rather than recomputing M and K.
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    rsrc = buffer_ops.create_buffer_resource(memref_ptr)
    elem_ir = elem_dtype() if callable(elem_dtype) else elem_dtype

    warp_tile_m = tile_m // warps_m
    k_wmma_steps = tile_k // WMMA_K
    wmma_m_rep = warp_tile_m // WMMA_M

    # Build result vector
    if isinstance(elem_ir, ir.FloatType):
        zero_attr = ir.FloatAttr.get(elem_ir, 0.0)
    else:
        zero_attr = ir.IntegerAttr.get(elem_ir, 0)
    zero_elem = std_arith.ConstantOp(elem_ir, zero_attr).result
    result_type = ir.VectorType.get([n_elems], elem_ir)
    result_vec = _vec_dialect.broadcast(result_type, zero_elem)

    for wm in range(wmma_m_rep):
        for ks in range(k_wmma_steps):
            for j in range(16):
                flat_idx = wm * (k_wmma_steps * 16) + ks * 16 + j
                # Use pre-computed per-element offset from MLIR (already encodes M and K)
                off = _vec_dialect.extract(offsets, [], [flat_idx])
                # Apply per-element mask
                mask_i = None
                if masks is not None:
                    mask_i = _vec_dialect.extract(masks, [], [flat_idx])
                val_i = buffer_ops.buffer_load(rsrc, off, vec_width=1, dtype=elem_ir, mask=mask_i)
                result_vec = _vec_dialect.insert(val_i, result_vec, [], [flat_idx])

    return result_vec


def _buffer_store_vec(data_vec, memref_ptr, offsets, masks, n_elems, elem_dtype):
    """Emulate amdg.buffer_store (warp-collective vector store) via per-element buffer_store.

    Args:
        data_vec: vector<NxType> data to store
        memref_ptr: memref value (global memory tensor pointer)
        offsets: vector<NxI32> of per-element offsets (in elements)
        masks: vector<NxI1> of per-element masks (or None)
        n_elems: number of elements in the result vector
        elem_dtype: element FlyDSL type class (e.g. T.bf16, T.f32)
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    from flydsl._mlir.dialects import scf as _scf_d
    rsrc = buffer_ops.create_buffer_resource(memref_ptr)
    for i in range(n_elems):
        val_i = _vec_dialect.extract(data_vec, [], [i])
        off_i = _vec_dialect.extract(offsets, [], [i])
        if masks is not None:
            mask_i = _vec_dialect.extract(masks, [], [i])
            # Use scf.if for conditional store: avoids the broken sentinel-offset
            # approach (buffer_store mask=... sets offset=0x7FFFFFFF which is
            # still in-bounds for an unbounded buffer and causes SIGSEGV).
            if_op = _scf_d.IfOp(mask_i, [], has_else=False)
            with ir.InsertionPoint(if_op.then_block):
                buffer_ops.buffer_store(val_i, rsrc, off_i)
                _scf_d.YieldOp([])
        else:
            buffer_ops.buffer_store(val_i, rsrc, off_i)



# SmemAllocator: total LDS = 131072 bytes
_lds_allocator = SmemAllocator(None, arch="gfx1250", global_sym_name="kernel_smem")
_lds_allocator.ptr = 131072

_LDS_OFFSET__v27 = 0  # byte offset
_LDS_ELEMS__v27 = 32768  # total elements
_LDS_OFFSET__v34 = 65536  # byte offset
_LDS_ELEMS__v34 = 32768  # total elements

@flyc.kernel
def attn_fwd_kernel(Q: fx.Tensor, K: fx.Tensor, V: fx.Tensor, O: fx.Tensor, stride_qz: fx.Int32, stride_qh: fx.Int32, stride_qm: fx.Int32, stride_kz: fx.Int32, stride_kh: fx.Int32, stride_kn: fx.Int32, stride_vz: fx.Int32, stride_vh: fx.Int32, stride_vn: fx.Int32, stride_oz: fx.Int32, stride_oh: fx.Int32, stride_om: fx.Int32):
    Q = Q.value
    K = K.value
    V = V.value
    O = O.value
    stride_qz = stride_qz.ir_value()
    stride_qh = stride_qh.ir_value()
    stride_qm = stride_qm.ir_value()
    stride_kz = stride_kz.ir_value()
    stride_kh = stride_kh.ir_value()
    stride_kn = stride_kn.ir_value()
    stride_vz = stride_vz.ir_value()
    stride_vh = stride_vh.ir_value()
    stride_vn = stride_vn.ir_value()
    stride_oz = stride_oz.ir_value()
    stride_oh = stride_oh.ir_value()
    stride_om = stride_om.ir_value()
    
    # Get LDS base memref from SmemAllocator
    _lds_base = _lds_allocator.get_base()
    
    cst = arith.constant_vector(1.44269502, T.vec(128, T.f32))
    cst_0 = arith.constant_vector(0.0883883461, T.vec(128, T.f32))
    cst_1 = arith.constant_vector(1.44269502, T.vec(2, T.f32))
    cst_2 = arith.constant_vector(0.0883883461, T.vec(2, T.f32))
    cst_3 = arith.constant_vector(float('-inf'), T.vec(128, T.f32))
    cst_4 = arith.constant_vector(1024, T.vec(64, T.i32))
    c1_i32 = arith.constant(1, type=T.i32)
    cst_5 = arith.constant_vector(1.0, T.vec(16, T.f32))
    c0_i32 = arith.constant(0, type=T.i32)
    cst_6 = arith.constant_vector(0.0, T.vec(128, T.f32))
    cst_7 = arith.constant_vector(1.0, T.vec(2, T.f32))
    cst_8 = arith.constant_vector(float('-inf'), T.vec(2, T.f32))
    cst_9 = arith.constant_vector(1024, T.vec(16, T.i32))
    cst_10 = arith.constant_vector(1024, T.vec(32, T.i32))
    c1_i64 = arith.constant(1, type=T.i64)
    c1024_i32 = arith.constant(1024, type=T.i32)
    c128_i32 = arith.constant(128, type=T.i32)
    _v0 = arith.index_cast(T.i32, gpu.block_id("x"))
    _v1 = arith.index_cast(T.i32, gpu.block_id("y"))
    _v2 = arith.index_cast(T.i32, gpu.block_id("z"))
    _v3 = _v2 * c128_i32
    _v4 = stride_qz * _v0
    _v5 = stride_qh * _v1
    _v6 = _v4 + _v5
    thread_id_x = gpu.thread_id("x")
    _v7 = arith.index_cast(T.i32, thread_id_x) if str(getattr(thread_id_x, "type", "")) != str(T.i32) else thread_id_x
    _v8_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (1, 2, 4, 8, 0, 16, 32))
    _v8_base = (_v7 % 2) * 1 + ((_v7 // 2) % 2) * 2 + ((_v7 // 4) % 2) * 4 + ((_v7 // 8) % 2) * 8 + ((_v7 // 16) % 2) * 0 + ((_v7 // 32) % 2) * 16 + ((_v7 // 64) % 2) * 32
    _v8 = vector.from_elements(T.vec(2, T.i32), [_v8_base, _v8_base + 64])
    _v9 = vector.broadcast(T.vec(2, T.i32), _v3)
    _v10 = _v9 + _v8
    _v11 = vector.shuffle(_v10, _v10, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    _v12 = vector.broadcast(T.vec(32, T.i32), stride_qm)
    _v13 = _v12 * _v11
    _v14 = vector.broadcast(T.vec(32, T.i32), _v6)
    _v15 = _v14 + _v13
    thread_id_x_11 = gpu.thread_id("x")
    _v16 = arith.index_cast(T.i32, thread_id_x_11) if str(getattr(thread_id_x_11, "type", "")) != str(T.i32) else thread_id_x_11
    _v17_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (0, 0, 0, 0, 8, 0, 0))
    _v17_base = (_v16 % 2) * 0 + ((_v16 // 2) % 2) * 0 + ((_v16 // 4) % 2) * 0 + ((_v16 // 8) % 2) * 0 + ((_v16 // 16) % 2) * 8 + ((_v16 // 32) % 2) * 0 + ((_v16 // 64) % 2) * 0
    _v17 = vector.from_elements(T.vec(64, T.i32), [_v17_base, _v17_base + 1, _v17_base + 2, _v17_base + 3, _v17_base + 4, _v17_base + 5, _v17_base + 6, _v17_base + 7, _v17_base + 16, _v17_base + 17, _v17_base + 18, _v17_base + 19, _v17_base + 20, _v17_base + 21, _v17_base + 22, _v17_base + 23, _v17_base + 32, _v17_base + 33, _v17_base + 34, _v17_base + 35, _v17_base + 36, _v17_base + 37, _v17_base + 38, _v17_base + 39, _v17_base + 48, _v17_base + 49, _v17_base + 50, _v17_base + 51, _v17_base + 52, _v17_base + 53, _v17_base + 54, _v17_base + 55, _v17_base + 64, _v17_base + 65, _v17_base + 66, _v17_base + 67, _v17_base + 68, _v17_base + 69, _v17_base + 70, _v17_base + 71, _v17_base + 80, _v17_base + 81, _v17_base + 82, _v17_base + 83, _v17_base + 84, _v17_base + 85, _v17_base + 86, _v17_base + 87, _v17_base + 96, _v17_base + 97, _v17_base + 98, _v17_base + 99, _v17_base + 100, _v17_base + 101, _v17_base + 102, _v17_base + 103, _v17_base + 112, _v17_base + 113, _v17_base + 114, _v17_base + 115, _v17_base + 116, _v17_base + 117, _v17_base + 118, _v17_base + 119])
    _v18 = vector.shuffle(_v15, _v15, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16])
    _v19 = vector.shuffle(_v17, _v17, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])
    _v20 = _v18 + _v19
    _v21 = stride_kz * _v0
    _v22 = _addptr(K, _v21, elem_bytes=2)  # addptr
    _v23 = stride_kh * _v1
    _v24 = _addptr(_v22, _v23, elem_bytes=2)  # addptr
    _v25 = arith.extsi(T.i64, stride_kn)
    _v26 = _make_tdm_desc(_v24, [c1024_i32, c128_i32], [_v25, c1_i64], elem_bytes=2, tile_shape=(128, 128), num_warps=1)
    _v27 = SmemPtr(_lds_base, _LDS_OFFSET__v27, T.bf16, shape=(_LDS_ELEMS__v27,)).get()  # LDS alloc via SmemAllocator
    _v28 = stride_vz * _v0
    _v29 = _addptr(V, _v28, elem_bytes=2)  # addptr
    _v30 = stride_vh * _v1
    _v31 = _addptr(_v29, _v30, elem_bytes=2)  # addptr
    _v32 = arith.extsi(T.i64, stride_vn)
    _v33 = _make_tdm_desc(_v31, [c1024_i32, c128_i32], [_v32, c1_i64], elem_bytes=2, tile_shape=(128, 128), num_warps=1)
    _v34 = SmemPtr(_lds_base, _LDS_OFFSET__v34, T.bf16, shape=(_LDS_ELEMS__v34,)).get()  # LDS alloc via SmemAllocator
    _v35 = _v11 < cst_10
    _v36 = vector.shuffle(_v35, _v35, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16])
    _v37 = _buffer_load_dot_op_a(Q, _v20, _v36, 128, T.bf16,
                                      tile_m=128, tile_k=128, warps_m=4, warps_n=1, stride_m=stride_qm)
    _v38 = stride_oz * _v0
    _v39 = stride_oh * _v1
    _v40 = _v38 + _v39
    thread_id_x_12 = gpu.thread_id("x")
    _v41 = arith.index_cast(T.i32, thread_id_x_12) if str(getattr(thread_id_x_12, "type", "")) != str(T.i32) else thread_id_x_12
    _v42_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (1, 2, 4, 8, 0, 16, 32))
    _v42_base = (_v41 % 2) * 1 + ((_v41 // 2) % 2) * 2 + ((_v41 // 4) % 2) * 4 + ((_v41 // 8) % 2) * 8 + ((_v41 // 16) % 2) * 0 + ((_v41 // 32) % 2) * 16 + ((_v41 // 64) % 2) * 32
    _v42 = vector.from_elements(T.vec(2, T.i32), [_v42_base, _v42_base + 64])
    _v43 = vector.broadcast(T.vec(2, T.i32), _v3)
    _v44 = _v43 + _v42
    _v45 = vector.shuffle(_v44, _v44, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v46 = vector.broadcast(T.vec(16, T.i32), stride_om)
    _v47 = _v46 * _v45
    _v48 = vector.broadcast(T.vec(16, T.i32), _v40)
    _v49 = _v48 + _v47
    thread_id_x_13 = gpu.thread_id("x")
    _v50 = arith.index_cast(T.i32, thread_id_x_13) if str(getattr(thread_id_x_13, "type", "")) != str(T.i32) else thread_id_x_13
    _v51_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (0, 0, 0, 0, 8, 0, 0))
    _v51_base = (_v50 % 2) * 0 + ((_v50 // 2) % 2) * 0 + ((_v50 // 4) % 2) * 0 + ((_v50 // 8) % 2) * 0 + ((_v50 // 16) % 2) * 8 + ((_v50 // 32) % 2) * 0 + ((_v50 // 64) % 2) * 0
    _v51 = vector.from_elements(T.vec(64, T.i32), [_v51_base, _v51_base + 1, _v51_base + 2, _v51_base + 3, _v51_base + 4, _v51_base + 5, _v51_base + 6, _v51_base + 7, _v51_base + 16, _v51_base + 17, _v51_base + 18, _v51_base + 19, _v51_base + 20, _v51_base + 21, _v51_base + 22, _v51_base + 23, _v51_base + 32, _v51_base + 33, _v51_base + 34, _v51_base + 35, _v51_base + 36, _v51_base + 37, _v51_base + 38, _v51_base + 39, _v51_base + 48, _v51_base + 49, _v51_base + 50, _v51_base + 51, _v51_base + 52, _v51_base + 53, _v51_base + 54, _v51_base + 55, _v51_base + 64, _v51_base + 65, _v51_base + 66, _v51_base + 67, _v51_base + 68, _v51_base + 69, _v51_base + 70, _v51_base + 71, _v51_base + 80, _v51_base + 81, _v51_base + 82, _v51_base + 83, _v51_base + 84, _v51_base + 85, _v51_base + 86, _v51_base + 87, _v51_base + 96, _v51_base + 97, _v51_base + 98, _v51_base + 99, _v51_base + 100, _v51_base + 101, _v51_base + 102, _v51_base + 103, _v51_base + 112, _v51_base + 113, _v51_base + 114, _v51_base + 115, _v51_base + 116, _v51_base + 117, _v51_base + 118, _v51_base + 119])
    _v52 = vector.shuffle(_v49, _v49, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])
    _v53 = vector.shuffle(_v51, _v51, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])
    _v54 = _v52 + _v53
    _v55 = _v45 < cst_9
    _for_ctx__v56_3 = _SCFForCtx(c0_i32, c1024_i32, c128_i32, [cst_8, cst_7, cst_6])
    with _for_ctx__v56_3 as (_iv_index, [arg17, arg18, arg19]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v62 = _v27  # memdesc_index[c0_i32]
        _v63 = _tdm_copy_to_lds(_v26, (arg16, c0_i32), _v62)
        _v64 = tdm_ops.tensor_wait(0)
        gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
        _v65 = (_v62, True)  # memdesc_trans → (memref, transposed=True)
        _v66 = _v65  # fly.lds_load with precomputed offsets → passthrough
        # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
        _v67 = _wmma_gemm_full(_v37, _v66, cst_6, T.bf16, warps_m=4, warps_n=1)
        _v68 = vector.broadcast(T.vec(64, T.i32), arg16)
        _v69 = _v68 + _v51
        _v70 = _v69 < cst_4
        _v71 = vector.shuffle(_v70, _v70, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])
        _v72 = arith.select(_v71, _v67, cst_3)
        cst_14 = arith.constant_vector(0.0, T.vec(2, T.f32))
        _v73 = vector.extract(_v72, static_position=[0])
        c1 = arith.constant(1, type=T.index)
        c64 = arith.constant(64, type=T.index)
        c1_15 = arith.constant(1, type=T.index)
        _for_ctx__v74 = _SCFForCtx(c1, c64, c1_15, [_v73])
        with _for_ctx__v74 as (_iv_index, [arg21]):
            arg20 = arith.index_cast(T.i32, _iv_index)
            _v150 = arith.index_cast(T.i32, arg20) if str(getattr(arg20, "type", "")) != str(T.i32) else arg20
            c0_i32_39 = arith.constant(0, type=T.i32)
            _v151 = c0_i32_39 + _v150
            _v152 = llvm_dialect.extractelement(_v72, _v151)
            _v153 = arith.maxnumf(arg21, _v152)
            _scf_yield_([_v153])
        _v74 = _for_ctx__v74.results[0]
        _v75 = vector.insert(_v74, cst_14, static_position=[0], dynamic_position=[])
        _v76 = vector.extract(_v72, static_position=[64])
        c1_16 = arith.constant(1, type=T.index)
        c64_17 = arith.constant(64, type=T.index)
        c1_18 = arith.constant(1, type=T.index)
        _for_ctx__v77 = _SCFForCtx(c1_16, c64_17, c1_18, [_v76])
        with _for_ctx__v77 as (_iv_index, [arg21]):
            arg20 = arith.index_cast(T.i32, _iv_index)
            _v150 = arith.index_cast(T.i32, arg20) if str(getattr(arg20, "type", "")) != str(T.i32) else arg20
            c64_i32 = arith.constant(64, type=T.i32)
            _v151 = c64_i32 + _v150
            _v152 = llvm_dialect.extractelement(_v72, _v151)
            _v153 = arith.maxnumf(arg21, _v152)
            _scf_yield_([_v153])
        _v77 = _for_ctx__v77.results[0]
        _v78 = vector.insert(_v77, _v75, static_position=[1], dynamic_position=[])
        _v79 = vector.extract(_v78, static_position=[0])
        thread_id_x_19 = gpu.thread_id("x")
        _v80 = arith.index_cast(T.i32, thread_id_x_19) if str(getattr(thread_id_x_19, "type", "")) != str(T.i32) else thread_id_x_19
        c32_i32 = arith.constant(32, type=T.i32)
        _v81 = _v80 % c32_i32
        c16_i32 = arith.constant(16, type=T.i32)
        _v82 = _v81 ^ c16_i32
        c2_i32 = arith.constant(2, type=T.i32)
        _v83 = _v82 << c2_i32
        _v84 = arith.bitcast(T.i32, _v79)
        _v85 = rocdl.ds_bpermute(T.i32, _v83, _v84)
        _v86 = arith.bitcast(T.f32, _v85)
        _v87 = arith.maxnumf(_v79, _v86)
        _v88 = vector.insert(_v87, _v78, static_position=[0], dynamic_position=[])
        _v89 = vector.extract(_v88, static_position=[1])
        thread_id_x_20 = gpu.thread_id("x")
        _v90 = arith.index_cast(T.i32, thread_id_x_20) if str(getattr(thread_id_x_20, "type", "")) != str(T.i32) else thread_id_x_20
        c32_i32_21 = arith.constant(32, type=T.i32)
        _v91 = _v90 % c32_i32_21
        c16_i32_22 = arith.constant(16, type=T.i32)
        _v92 = _v91 ^ c16_i32_22
        c2_i32_23 = arith.constant(2, type=T.i32)
        _v93 = _v92 << c2_i32_23
        _v94 = arith.bitcast(T.i32, _v89)
        _v95 = rocdl.ds_bpermute(T.i32, _v93, _v94)
        _v96 = arith.bitcast(T.f32, _v95)
        _v97 = arith.maxnumf(_v89, _v96)
        _v98 = vector.insert(_v97, _v88, static_position=[1], dynamic_position=[])
        _v99 = arith.maxnumf(arg17, _v98)
        _v100 = _v99 * cst_2
        _v101 = _v100 * cst_1
        _v102 = _v72 * cst_0
        _v103 = _v102 * cst
        _v104 = vector.shuffle(_v101, _v101, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
        _v105 = vector.shuffle(_v104, _v104, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])
        _v106 = _v103 - _v105
        _v107 = math_dialect.exp2(_v106)
        _v108 = arg17 * cst_2
        _v109 = _v108 * cst_1
        _v110 = _v109 - _v101
        _v111 = math_dialect.exp2(_v110)
        cst_24 = arith.constant_vector(0.0, T.vec(2, T.f32))
        _v112 = vector.extract(_v107, static_position=[0])
        c1_25 = arith.constant(1, type=T.index)
        c64_26 = arith.constant(64, type=T.index)
        c1_27 = arith.constant(1, type=T.index)
        _for_ctx__v113 = _SCFForCtx(c1_25, c64_26, c1_27, [_v112])
        with _for_ctx__v113 as (_iv_index, [arg21]):
            arg20 = arith.index_cast(T.i32, _iv_index)
            _v150 = arith.index_cast(T.i32, arg20) if str(getattr(arg20, "type", "")) != str(T.i32) else arg20
            c0_i32_39 = arith.constant(0, type=T.i32)
            _v151 = c0_i32_39 + _v150
            _v152 = llvm_dialect.extractelement(_v107, _v151)
            _v153 = arg21 + _v152
            _scf_yield_([_v153])
        _v113 = _for_ctx__v113.results[0]
        _v114 = vector.insert(_v113, cst_24, static_position=[0], dynamic_position=[])
        _v115 = vector.extract(_v107, static_position=[64])
        c1_28 = arith.constant(1, type=T.index)
        c64_29 = arith.constant(64, type=T.index)
        c1_30 = arith.constant(1, type=T.index)
        _for_ctx__v116 = _SCFForCtx(c1_28, c64_29, c1_30, [_v115])
        with _for_ctx__v116 as (_iv_index, [arg21]):
            arg20 = arith.index_cast(T.i32, _iv_index)
            _v150 = arith.index_cast(T.i32, arg20) if str(getattr(arg20, "type", "")) != str(T.i32) else arg20
            c64_i32 = arith.constant(64, type=T.i32)
            _v151 = c64_i32 + _v150
            _v152 = llvm_dialect.extractelement(_v107, _v151)
            _v153 = arg21 + _v152
            _scf_yield_([_v153])
        _v116 = _for_ctx__v116.results[0]
        _v117 = vector.insert(_v116, _v114, static_position=[1], dynamic_position=[])
        _v118 = vector.extract(_v117, static_position=[0])
        thread_id_x_31 = gpu.thread_id("x")
        _v119 = arith.index_cast(T.i32, thread_id_x_31) if str(getattr(thread_id_x_31, "type", "")) != str(T.i32) else thread_id_x_31
        c32_i32_32 = arith.constant(32, type=T.i32)
        _v120 = _v119 % c32_i32_32
        c16_i32_33 = arith.constant(16, type=T.i32)
        _v121 = _v120 ^ c16_i32_33
        c2_i32_34 = arith.constant(2, type=T.i32)
        _v122 = _v121 << c2_i32_34
        _v123 = arith.bitcast(T.i32, _v118)
        _v124 = rocdl.ds_bpermute(T.i32, _v122, _v123)
        _v125 = arith.bitcast(T.f32, _v124)
        _v126 = _v118 + _v125
        _v127 = vector.insert(_v126, _v117, static_position=[0], dynamic_position=[])
        _v128 = vector.extract(_v127, static_position=[1])
        thread_id_x_35 = gpu.thread_id("x")
        _v129 = arith.index_cast(T.i32, thread_id_x_35) if str(getattr(thread_id_x_35, "type", "")) != str(T.i32) else thread_id_x_35
        c32_i32_36 = arith.constant(32, type=T.i32)
        _v130 = _v129 % c32_i32_36
        c16_i32_37 = arith.constant(16, type=T.i32)
        _v131 = _v130 ^ c16_i32_37
        c2_i32_38 = arith.constant(2, type=T.i32)
        _v132 = _v131 << c2_i32_38
        _v133 = arith.bitcast(T.i32, _v128)
        _v134 = rocdl.ds_bpermute(T.i32, _v132, _v133)
        _v135 = arith.bitcast(T.f32, _v134)
        _v136 = _v128 + _v135
        _v137 = vector.insert(_v136, _v127, static_position=[1], dynamic_position=[])
        _v138 = vector.shuffle(_v111, _v111, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
        _v139 = vector.shuffle(_v138, _v138, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])
        _v140 = arg19 * _v139
        _v141 = arith.truncf(T.vec(128, T.bf16), _v107)
        _v142 = arg18 * _v111
        _v143 = _v142 + _v137
        _v144 = _v34  # memdesc_index[c0_i32]
        _v145 = _tdm_copy_to_lds(_v33, (arg16, c0_i32), _v144)
        _v146 = tdm_ops.tensor_wait(0)
        gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
        _v147 = _v144  # fly.lds_load with precomputed offsets → passthrough
        _v148 = _v141  # P→A: direct passthrough (flat_idx_C == flat_idx_A for this WMMA config)
        # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
        _v149 = _wmma_gemm_full(_v148, _v147, _v140, T.bf16, warps_m=4, warps_n=1)
        _scf_yield_([_v99, _v143, _v149])
    _v56_r0 = _for_ctx__v56_3.results[0]
    _v56_r1 = _for_ctx__v56_3.results[1]
    _v56_r2 = _for_ctx__v56_3.results[2]
    _v57 = vector.shuffle(_v56_r1, _v56_r1, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v58 = cst_5 / _v57
    _v59 = vector.shuffle(_v58, _v58, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])
    _v60 = _v56_r2 * _v59
    _v61 = vector.shuffle(_v55, _v55, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])
    _buffer_store_vec(_v60, O, _v54, _v61, 128, T.f32)
    return
