"""
FlyDSL kernel generated from Fly MLIR
Target: hip:gfx1250
Warps: 4, Threads/Warp: 32

Generated by triton.tools.fly_to_flydsl
"""

import math
import flydsl.expr as fx
import flydsl.compiler as flyc
from flydsl.expr import arith, vector, gpu, rocdl, buffer_ops
from flydsl.expr.rocdl import tdm_ops
from flydsl.expr.typing import T
from flydsl._mlir.dialects import math as math_dialect
from flydsl._mlir import ir
from flydsl._mlir.dialects import llvm as llvm_dialect
from flydsl._mlir.dialects import arith as std_arith
from flydsl._mlir.dialects import memref as memref_dialect
from flydsl._mlir.dialects import fly as _fly_d
from flydsl.expr.utils.arith import ArithValue as _ArithValue
from flydsl._mlir.dialects import scf as _scf_dialect
from flydsl.utils.smem_allocator import SmemAllocator, SmemPtr
from flydsl.compiler.jit_function import CompilationContext

NUM_WARPS = 4
THREADS_PER_WARP = 32
TARGET = "hip:gfx1250"

def _addptr(base, offset, elem_bytes=2):
    """Triton-style pointer arithmetic: base + offset * elem_bytes.

    If base is a memref, extracts the raw LLVM pointer first.
    Returns an i64 byte address.
    """
    i64 = ir.IntegerType.get_signless(64)
    i32 = ir.IntegerType.get_signless(32)
    # Extract raw pointer from memref if needed
    base_val = base
    if hasattr(base, "type") and "memref" in str(base.type):
        glb_ptr_type = ir.Type.parse("!llvm.ptr<1>")
        base_ptr = _fly_d.extract_aligned_pointer_as_index(glb_ptr_type, base)
        base_val = _ArithValue(llvm_dialect.ptrtoint(i64, base_ptr))
    elif hasattr(base, "type") and str(base.type) == "i64":
        base_val = _ArithValue(base)
    else:
        # Already an i64 byte address
        base_val = _ArithValue(base) if not isinstance(base, _ArithValue) else base
    # Convert offset to i64 byte offset
    offset_val = offset
    if hasattr(offset, "type") and str(offset.type) == "i32":
        offset_val = std_arith.ExtSIOp(i64, offset).result
    elem_bytes_val = std_arith.ConstantOp(i64, ir.IntegerAttr.get(i64, elem_bytes)).result
    byte_offset = _ArithValue(std_arith.MulIOp(offset_val, elem_bytes_val).result)
    return _ArithValue(std_arith.AddIOp(base_val, byte_offset).result)


def _make_tdm_desc(base_addr_i64, shapes, strides, elem_bytes=2, tile_shape=None, num_warps=1, pad_interval=0, pad_amount=0):
    """Construct a TDM descriptor from a raw i64 byte address + shapes + strides.

    tile_shape: (outer_tile, inner_tile) static tile dimensions for the TDM descriptor.
    num_warps: number of warps in the workgroup (for per-warp distribution).
    pad_interval: padded_shared interval in elements (0 = no padding).
    pad_amount: padded_shared pad amount in elements (0 = no padding).
    Returns a TDMDescriptor2D (dgroup0, dgroup1) with per-warp metadata.
    """
    i32 = ir.IntegerType.get_signless(32)
    i64 = ir.IntegerType.get_signless(64)

    from flydsl.expr import rocdl as _rocdl_ext
    from flydsl.expr.rocdl.tdm_ops import compute_warp_distribution
    outer_stride = strides[0]

    # Tile shape
    if tile_shape is not None:
        _tile_outer, _tile_inner = tile_shape
    else:
        _tile_outer = _tile_inner = 128

    # Per-warp distribution (matches tdm_ops.make_tensor_descriptor_2d)
    _warps_per_dim, _block_per_warp = compute_warp_distribution(
        [_tile_outer, _tile_inner], num_warps)
    bpw_outer, bpw_inner = _block_per_warp
    warps_dim0 = _warps_per_dim[0]

    # Get base address
    glb_addr_i64 = _ArithValue(base_addr_i64)

    # Per-warp global address offset via wave_id
    if num_warps > 1:
        _wid_i32 = _rocdl_ext.wave_id()
        _wid_idx = arith.index_cast(T.index, _wid_i32)
        _warp_coord_outer = _wid_idx % arith.index(warps_dim0)
        _warp_coord_inner = _wid_idx / arith.index(warps_dim0)
        _warp_off_outer = _warp_coord_outer * arith.index(bpw_outer)
        _warp_off_inner = _warp_coord_inner * arith.index(bpw_inner)
        # Global byte offset: (warp_off_outer * outer_stride + warp_off_inner) * elem_bytes
        if hasattr(outer_stride, "type") and str(outer_stride.type) == "i64":
            _stride_idx = arith.index_cast(T.index, std_arith.TruncIOp(i32, outer_stride).result)
        elif hasattr(outer_stride, "type") and str(outer_stride.type) == "i32":
            _stride_idx = arith.index_cast(T.index, outer_stride)
        else:
            _stride_idx = arith.index(int(outer_stride) if not hasattr(outer_stride, "type") else 1)
        _warp_elem_off = _warp_off_outer * _stride_idx + _warp_off_inner
        _warp_byte_off = _warp_elem_off * arith.index(elem_bytes)
        _warp_byte_off_i64 = arith.index_cast(T.i64, _warp_byte_off)
        glb_addr_i64 = _ArithValue(std_arith.AddIOp(glb_addr_i64, _warp_byte_off_i64).result)

    # LDS address placeholder (will be filled by tdm_copy)
    lds_addr_i32 = arith.constant(0, type=T.i32)

    # GROUP0: pred, lds_addr, global_addr_lo/hi
    g0_s0 = arith.constant(1, type=T.i32)  # pred = enabled
    g0_s1 = lds_addr_i32
    g0_s2 = _ArithValue(std_arith.TruncIOp(i32, glb_addr_i64).result)
    hi_raw = _ArithValue(glb_addr_i64).shrui(arith.constant(32, type=T.i64))
    g0_s3 = _ArithValue(std_arith.TruncIOp(i32, hi_raw).result) | arith.constant(1 << 31, type=T.i32)
    dgroup0 = vector.from_elements(T.vec(4, T.i32), [g0_s0, g0_s1, g0_s2, g0_s3])

    # GROUP1: config + tensor dims + tile (using per-warp dims)
    data_size_code = int(math.log2(elem_bytes))
    if pad_interval > 0 and pad_amount > 0:
        elem_bits = elem_bytes * 8
        interval_dw = pad_interval * elem_bits // 32
        amount_dw = pad_amount * elem_bits // 32
        enc_interval = int(math.log2(interval_dw)) - 1 if interval_dw > 0 else 0
        enc_amount = amount_dw - 1 if amount_dw > 0 else 0
        g1_s0_upper = (data_size_code << 16) | (1 << 20) | (enc_interval << 22) | (enc_amount << 25)
    else:
        g1_s0_upper = (data_size_code << 16)
    g1_s0 = arith.constant(g1_s0_upper, type=T.i32)
    # Per-warp dims: dim0=innermost=bpw_inner, dim1=outermost=bpw_outer
    # Matches tdm_ops.make_tensor_descriptor_2d encoding
    g1_s1 = arith.constant((bpw_inner & 0xFFFF) << 16, type=T.i32)   # tdim0_lo
    g1_s2 = arith.constant((bpw_outer & 0xFFFF) << 16, type=T.i32)   # tdim1_lo
    g1_s3 = arith.constant(bpw_inner << 16, type=T.i32)               # tile_d0
    g1_s4 = arith.constant(bpw_outer & 0xFFFF, type=T.i32)            # tile_d1
    # stride (outer stride in elements)
    if hasattr(outer_stride, "type") and str(outer_stride.type) == "i64":
        g1_s5 = _ArithValue(std_arith.TruncIOp(i32, outer_stride).result)
    else:
        g1_s5 = outer_stride
    g1_s6 = arith.constant(0, type=T.i32)
    g1_s7 = arith.constant(0, type=T.i32)
    dgroup1 = vector.from_elements(
        T.vec(8, T.i32), [g1_s0, g1_s1, g1_s2, g1_s3, g1_s4, g1_s5, g1_s6, g1_s7])

    desc = tdm_ops.TDMDescriptor2D(dgroup0=dgroup0, dgroup1=dgroup1)
    # Store per-warp metadata for _tdm_copy_to_lds
    desc._bpw_outer = bpw_outer
    desc._bpw_inner = bpw_inner
    desc._warps_dim0 = warps_dim0
    desc._tile_inner = _tile_inner
    desc._num_warps = num_warps
    desc._pad_amount = pad_amount
    return desc


# _lds_alloc removed — LDS allocation now uses SmemAllocator/SmemPtr


def _tdm_copy_to_lds(desc, offsets, dst, elem_bytes=2, pred=None):
    """TDM async copy from global to LDS.

    Creates an updated descriptor with:
    1. LDS target address from dst memref (with per-warp offset)
    2. Global source address offset by (outer_off * stride + inner_off)
    Then issues the async copy.
    """
    from flydsl._mlir.dialects import vector as _vec_d
    i32 = ir.IntegerType.get_signless(32)
    i64 = ir.IntegerType.get_signless(64)

    # Get LDS byte address from dst memref (or _LdsSubview)
    _sub_elem_off = None
    if isinstance(dst, _LdsSubview):
        _sub_elem_off = dst.elem_offset  # i32 element offset
        dst = dst.base_mr
    lds_base_idx = memref_dialect.extract_aligned_pointer_as_index(dst)
    # Add sub-buffer element offset (from _memdesc_index_subview) as bytes
    if _sub_elem_off is not None:
        _off_idx = arith.index_cast(T.index, _sub_elem_off)
        _off_bytes = _off_idx * arith.index(elem_bytes)
        lds_base_idx = std_arith.AddIOp(lds_base_idx, _off_bytes).result

    # Add per-warp LDS offset
    _nw = getattr(desc, "_num_warps", 1)
    if _nw > 1:
        from flydsl.expr import rocdl as _rocdl_ext
        _wid = arith.index_cast(T.index, _rocdl_ext.wave_id())
        _wco = _wid % arith.index(desc._warps_dim0)
        _wci = _wid / arith.index(desc._warps_dim0)
        _woo = _wco * arith.index(desc._bpw_outer)
        _woi = _wci * arith.index(desc._bpw_inner)
        # LDS inner stride = tile_inner + pad_amount (padded row width)
        _pad_amt = getattr(desc, "_pad_amount", 0)
        _lds_inner_stride = desc._tile_inner + _pad_amt
        _lds_warp_elem = _woo * arith.index(_lds_inner_stride) + _woi
        _lds_warp_bytes = _lds_warp_elem * arith.index(elem_bytes)
        lds_base_idx = std_arith.AddIOp(lds_base_idx,
            std_arith.IndexCastOp(ir.IndexType.get(), _lds_warp_bytes).result
            if not hasattr(_lds_warp_bytes, "type") or str(getattr(_lds_warp_bytes, "type", "")) != "index"
            else _lds_warp_bytes).result

    lds_addr_i32 = std_arith.IndexCastOp(i32, lds_base_idx).result

    # Build updated dgroup0 with correct LDS address
    g0_s0 = pred if pred is not None else _vec_d.extract(desc.dgroup0, [], [0])
    g0_s1 = lds_addr_i32  # LDS target address (includes per-warp offset)

    # Apply outer + inner offsets to global address
    # offsets = (outer_off, inner_off)
    outer_off_raw = offsets[0]
    if hasattr(outer_off_raw, "type") and str(outer_off_raw.type) == "i32":
        outer_off_i64 = std_arith.ExtSIOp(i64, outer_off_raw).result
    elif hasattr(outer_off_raw, "type") and str(outer_off_raw.type) == "i64":
        outer_off_i64 = outer_off_raw
    else:
        outer_off_i64 = std_arith.ExtSIOp(i64, outer_off_raw).result

    # Extract original global addr from dgroup0[2:3]
    orig_lo = _vec_d.extract(desc.dgroup0, [], [2])
    orig_hi = _vec_d.extract(desc.dgroup0, [], [3])
    # Reconstruct i64 global addr
    lo_i64 = std_arith.ExtUIOp(i64, orig_lo).result
    hi_masked = std_arith.AndIOp(orig_hi, std_arith.ConstantOp(i32, ir.IntegerAttr.get(i32, 0x7FFFFFFF)).result).result
    hi_i64 = std_arith.ExtUIOp(i64, hi_masked).result
    shift_32 = std_arith.ConstantOp(i64, ir.IntegerAttr.get(i64, 32)).result
    hi_shifted = std_arith.ShLIOp(hi_i64, shift_32).result
    orig_addr = std_arith.AddIOp(lo_i64, hi_shifted).result

    # Extract stride from dgroup1[5] (outer stride in elements)
    stride_i32 = _vec_d.extract(desc.dgroup1, [], [5])
    stride_i64 = std_arith.ExtSIOp(i64, stride_i32).result

    # off_bytes = (outer_off * stride + inner_off) * elem_bytes
    # inner_stride is always 1 for TDM descriptors (contiguous innermost)
    off_elems = std_arith.MulIOp(outer_off_i64, stride_i64).result
    # Add inner offset if present
    if len(offsets) > 1:
        inner_off_raw = offsets[1]
        if hasattr(inner_off_raw, "type") and str(inner_off_raw.type) == "i32":
            inner_off_i64 = std_arith.ExtSIOp(i64, inner_off_raw).result
        elif hasattr(inner_off_raw, "type") and str(inner_off_raw.type) == "i64":
            inner_off_i64 = inner_off_raw
        else:
            inner_off_i64 = std_arith.ExtSIOp(i64, inner_off_raw).result
        off_elems = std_arith.AddIOp(off_elems, inner_off_i64).result
    eb = std_arith.ConstantOp(i64, ir.IntegerAttr.get(i64, elem_bytes)).result
    off_bytes = std_arith.MulIOp(off_elems, eb).result
    new_addr = std_arith.AddIOp(orig_addr, off_bytes).result

    # Split new addr to lo/hi
    g0_s2 = std_arith.TruncIOp(i32, new_addr).result
    hi_raw = std_arith.ShRUIOp(new_addr, shift_32).result
    hi_trunc = std_arith.TruncIOp(i32, hi_raw).result
    type_bit = std_arith.ConstantOp(i32, ir.IntegerAttr.get(i32, 1 << 31)).result
    g0_s3 = std_arith.OrIOp(hi_trunc, type_bit).result

    new_dg0 = vector.from_elements(T.vec(4, T.i32), [g0_s0, g0_s1, g0_s2, g0_s3])

    updated_desc = tdm_ops.TDMDescriptor2D(dgroup0=new_dg0, dgroup1=desc.dgroup1)
    tdm_ops.tensor_load_2d(updated_desc)
    return dst


def _to_index(val):
    """Convert a value to MLIR index type."""
    if isinstance(val, ir.Value):
        if val.type == ir.IndexType.get():
            return val
        return std_arith.IndexCastOp(ir.IndexType.get(), val).result
    if hasattr(val, "ir_value"):
        raw = val.ir_value()
        if isinstance(raw, ir.Value) and raw.type != ir.IndexType.get():
            return std_arith.IndexCastOp(ir.IndexType.get(), raw).result
        return raw
    if isinstance(val, int):
        return std_arith.ConstantOp(ir.IndexType.get(), val).result
    raise TypeError(f"_to_index: unexpected type {type(val)}")


class _SCFForCtx:
    """Context manager for scf.for loop."""
    def __init__(self, lb, ub, step, init_vals=None):
        start = _to_index(lb)
        stop = _to_index(ub)
        step_v = _to_index(step)
        raw_inits = []
        if init_vals:
            for v in init_vals:
                if isinstance(v, ir.Value):
                    raw_inits.append(v)
                elif hasattr(v, "ir_value"):
                    raw_inits.append(v.ir_value())
                else:
                    raw_inits.append(v)
        if raw_inits:
            self.for_op = _scf_dialect.ForOp(start, stop, step_v, raw_inits)
        else:
            self.for_op = _scf_dialect.ForOp(start, stop, step_v)
        self.ip = ir.InsertionPoint(self.for_op.body)

    def __enter__(self):
        self.ip.__enter__()
        iv = self.for_op.induction_variable
        iargs = list(self.for_op.inner_iter_args) if self.for_op.inner_iter_args else []
        return iv, iargs

    def __exit__(self, *args):
        self.ip.__exit__(*args)

    @property
    def results(self):
        return list(self.for_op.results)


def _scf_yield_(vals):
    """Emit scf.yield with the given values."""
    raw = []
    for v in vals:
        if isinstance(v, ir.Value):
            raw.append(v)
        elif hasattr(v, "ir_value"):
            raw.append(v.ir_value())
        else:
            raw.append(v)
    _scf_dialect.YieldOp(raw)


class _LdsSubview:
    """Wrapper for a sub-buffer view into a multi-buffered LDS memref.

    Carries the base memref and an element offset so that both _tdm_copy_to_lds
    (which extracts the raw pointer) and _lds_load_gf2 (which loads by index)
    can correctly address the sub-buffer.
    """
    def __init__(self, base_mr, elem_offset_i32):
        self.base_mr = base_mr  # the full LDS memref
        self.elem_offset = elem_offset_i32  # i32 element offset within it
        # Expose .type so code expecting a memref-like object can inspect it
        self.type = base_mr.type


def _memdesc_index_subview(memref_or_tuple, idx, buffer_size, pad_interval=0, pad_amount=0):
    """Create a sub-view of a multi-buffered LDS memref at buffer idx.

    memref_or_tuple: the full LDS memref (or (memref, transposed) tuple).
    idx: buffer index (i32 or Python int).
    buffer_size: number of elements per buffer (unpadded).
    pad_interval: padded_shared interval in elements (0 = no padding).
    pad_amount: padded_shared pad amount in elements (0 = no padding).
    Returns the base memref (idx==0) or an _LdsSubview with element offset.
    """
    # Unwrap possible tuple
    if isinstance(memref_or_tuple, tuple):
        base_mr = memref_or_tuple[0]
    else:
        base_mr = memref_or_tuple

    # If idx is a compile-time 0, return the base memref (no offset needed)
    is_zero = False
    if isinstance(idx, int) and idx == 0:
        is_zero = True
    elif isinstance(idx, ir.Value):
        try:
            is_zero = ir.IntegerAttr(idx.owner.attributes["value"]).value == 0
        except:
            pass

    if is_zero:
        return base_mr

    # Compute element offset as i32 for downstream consumers
    if isinstance(idx, int):
        off_i32 = arith.constant(idx * buffer_size, type=T.i32)
    else:
        idx_i32 = idx if str(getattr(idx, "type", "")) == "i32" else arith.index_cast(T.i32, idx)
        off_i32 = idx_i32 * arith.constant(buffer_size, type=T.i32)

    # Apply padded_shared padding adjustment: off += (off >> log2(interval)) << log2(amount)
    if pad_interval > 0 and pad_amount > 0:
        _pi_shift = int(math.log2(pad_interval))
        _pa_shift = int(math.log2(pad_amount))
        pad_off = (off_i32 >> arith.constant(_pi_shift, type=T.i32)) << arith.constant(_pa_shift, type=T.i32)
        off_i32 = off_i32 + pad_off

    return _LdsSubview(base_mr, off_i32)


def _lds_load_gf2(lds_ref, reg_offsets, lane_bases, warp_bases, n_elems, elem_dtype, pad_interval=0, pad_amount=0):
    """Load n_elems from LDS using GF(2) XOR-based addressing.

    Each thread's per-element offset = lane_contribution XOR warp_contribution XOR reg_offset[i].
    reg_offsets: list of per-register-element byte offsets (length = n_elems).
    lane_bases: GF(2) basis vectors for lane_id bits.
    warp_bases: GF(2) basis vectors for warp_id bits.
    pad_interval: padded_shared interval in elements (0 = no padding).
    pad_amount: padded_shared pad amount in elements (0 = no padding).
    """
    from flydsl._mlir.dialects import memref as _mr_d
    from flydsl._mlir.dialects import vector as _vec_dialect

    # Unwrap LDS memref from possible (memref, transposed) tuple or _LdsSubview
    _sub_elem_off = None  # i32 element offset for sub-buffer
    if isinstance(lds_ref, tuple):
        inner = lds_ref[0]
        if isinstance(inner, _LdsSubview):
            _sub_elem_off = inner.elem_offset
            lds_flat = inner.base_mr
        else:
            lds_flat = inner
    elif isinstance(lds_ref, _LdsSubview):
        _sub_elem_off = lds_ref.elem_offset
        lds_flat = lds_ref.base_mr
    else:
        lds_flat = lds_ref

    tid = arith.index_cast(T.i32, gpu.thread_id("x"))
    lane = tid & arith.constant(31, type=T.i32)
    warp = (tid >> arith.constant(5, type=T.i32)) & arith.constant(3, type=T.i32)

    # Compute GF(2) lane contribution: XOR of (lane_bit_i * lane_bases[i])
    lane_c = arith.constant(0, type=T.i32)
    for bit, basis in enumerate(lane_bases):
        if basis == 0:
            continue
        lane_bit = (lane >> arith.constant(bit, type=T.i32)) & arith.constant(1, type=T.i32)
        lane_c = lane_c ^ (lane_bit * arith.constant(basis, type=T.i32))

    # Compute GF(2) warp contribution
    warp_c = arith.constant(0, type=T.i32)
    for bit, basis in enumerate(warp_bases):
        if basis == 0:
            continue
        warp_bit = (warp >> arith.constant(bit, type=T.i32)) & arith.constant(1, type=T.i32)
        warp_c = warp_c ^ (warp_bit * arith.constant(basis, type=T.i32))

    thr_base = lane_c ^ warp_c

    # Load each element from LDS at element offset = thr_base XOR reg_offsets[i]
    # For sub-buffer views, add the element offset AFTER the XOR (not before)
    # reg_offsets are element offsets (not byte offsets) from the C++ LinearLayout
    raw_dtype = elem_dtype
    if hasattr(raw_dtype, "ir_type"):
        raw_dtype = raw_dtype.ir_type()
    vec_type = ir.VectorType.get([n_elems], raw_dtype)
    # Pre-compute padding shift amounts (compile-time constants)
    _pad_i_shift = int(math.log2(pad_interval)) if pad_interval > 0 else 0
    _pad_a_shift = int(math.log2(pad_amount)) if pad_amount > 0 else 0
    elems = []
    for i in range(n_elems):
        elem_off = thr_base ^ arith.constant(reg_offsets[i], type=T.i32)
        # Apply padded_shared padding adjustment: off += (off >> log2(interval)) << log2(amount)
        if pad_interval > 0 and pad_amount > 0:
            pad_off = (elem_off >> arith.constant(_pad_i_shift, type=T.i32)) << arith.constant(_pad_a_shift, type=T.i32)
            elem_off = elem_off + pad_off
        if _sub_elem_off is not None:
            elem_off = elem_off + _sub_elem_off
        idx = arith.index_cast(T.index, elem_off)
        val = _mr_d.load(lds_flat, [idx])
        elems.append(val)
    return vector.from_elements(vec_type, elems)


def _wmma_gemm_full(a_data, b_lds_ref, c_vec, ab_dtype,
                     tile_m=128, tile_n=128, tile_k=128,
                     warps_m=4, warps_n=1, WMMA_M=16, WMMA_N=16, WMMA_K=32):
    """Complete tiled WMMA gemm: A (register vec) × B (LDS memref) → C (f32 vec).

    A is a flat per-thread register vector from buffer_load (dot_op opIdx=0 layout).
    B is a LDS memref from TDM copy, loaded with WMMA-aware per-element addressing.
    C is the per-thread accumulator vector (f32).

    warps_m/warps_n: how many warps split the M/N dimensions.
    For FA kernel: warps_m=4, warps_n=1 (4 warps along M, each does all N).

    Thread decomposition: lane16 = tid % 16, lane_kgrp = (tid // 16) % 2.
    A fragment: 16 consecutive elements from flat vec.
    B fragment: 16 elements loaded from LDS with WMMA addressing.
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    from flydsl._mlir.dialects import memref as _mr_d
    from flydsl.expr import rocdl

    raw_ab = ab_dtype
    if hasattr(raw_ab, "ir_type"):
        raw_ab = raw_ab.ir_type()
    is_bf16 = str(raw_ab) == "bf16"
    wmma_op = rocdl.wmma_f32_16x16x32_bf16 if is_bf16 else rocdl.wmma_f32_16x16x32_f16
    elem_ty = raw_ab

    # Unwrap values
    _a_sub_off = None  # i32 element offset for A sub-buffer
    if isinstance(a_data, _LdsSubview):
        _a_sub_off = a_data.elem_offset
        a_v = a_data.base_mr
    else:
        a_v = a_data.ir_value() if hasattr(a_data, "ir_value") else a_data
    c_v = c_vec.ir_value() if hasattr(c_vec, "ir_value") else c_vec

    # Check if a_data/b_lds_ref are flat register vectors (VectorType) vs LDS memref.
    # Both VectorType and MemRefType have .shape/.element_type, so use isinstance.
    a_is_vec = isinstance(a_v.type, ir.VectorType)

    # Check if B is already a pre-loaded register vector (from fly.lds_load with GF(2) offsets)
    b_raw = b_lds_ref.ir_value() if hasattr(b_lds_ref, "ir_value") else (b_lds_ref if isinstance(b_lds_ref, ir.Value) else None)
    b_is_vec = b_raw is not None and isinstance(b_raw.type, ir.VectorType)

    # ── CuTE layout definitions ──
    # Thread layout: (warps_m, warps_n, kgrp=2, lane=16)
    #   tid → (wave_m_idx, wave_n_idx, lane_kgrp, lane16)
    layout_thr = fx.make_layout(
        (warps_m, warps_n, 2, 16),
        (warps_n * 32, 32, 16, 1))

    # Thread decomposition via CuTE idx2crd
    tid_raw = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, tid_raw)
    thr_crd = _idx2crd(tid, layout_thr)
    wave_m_idx = fx.get(thr_crd, 0)
    wave_n_idx = fx.get(thr_crd, 1)
    lane_kgrp  = fx.get(thr_crd, 2)
    lane16     = fx.get(thr_crd, 3)

    warp_tile_m = tile_m // warps_m
    warp_tile_n = tile_n // warps_n
    wmma_m_rep = warp_tile_m // WMMA_M
    wmma_n_rep = warp_tile_n // WMMA_N
    k_wmma_steps = tile_k // WMMA_K
    n_accs = wmma_m_rep * wmma_n_rep

    # Warp-level M and N base offsets
    warp_m_off = wave_m_idx * arith.index(warp_tile_m)
    warp_n_off = wave_n_idx * arith.index(warp_tile_n)

    # Initialize accumulators from c_vec (8 f32 per WMMA result)
    c_per_wmma = 8
    wmma_result_type = ir.VectorType.get([c_per_wmma], ir.F32Type.get())
    accs = []
    for i in range(n_accs):
        c_slice_list = []
        for j in range(c_per_wmma):
            c_slice_list.append(_vec_dialect.extract(c_v, [], [i * c_per_wmma + j]))
        c_slice = vector.from_elements(wmma_result_type, c_slice_list)
        accs.append(c_slice)

    # Get B operand: pre-loaded register vector or LDS memref
    # b_lds_ref may be a (memref, transposed=True) tuple from memdesc_trans
    # or an _LdsSubview from _memdesc_index_subview
    b_transposed = False
    _b_sub_off = None  # i32 element offset for sub-buffer
    if not b_is_vec:
        if isinstance(b_lds_ref, tuple):
            b_inner = b_lds_ref[0]
            b_transposed = b_lds_ref[1] if len(b_lds_ref) > 1 else False
            if isinstance(b_inner, _LdsSubview):
                _b_sub_off = b_inner.elem_offset
                b_lds_flat = b_inner.base_mr
            else:
                b_lds_flat = b_inner
        elif isinstance(b_lds_ref, _LdsSubview):
            _b_sub_off = b_lds_ref.elem_offset
            b_lds_flat = b_lds_ref.base_mr
        else:
            b_lds_flat = b_lds_ref

    a_frag_type = ir.VectorType.get([16], elem_ty)
    b_frag_type = ir.VectorType.get([16], elem_ty)

    # LDS layouts for crd2idx-based offset computation (only needed when B is memref)
    if not b_is_vec:
        if b_transposed:
            layout_lds_b = fx.make_layout((tile_n, tile_k), (tile_k, 1))
        else:
            layout_lds_b = fx.make_layout((tile_k, tile_n), (tile_n, 1))
    layout_lds_a = fx.make_layout((tile_m, tile_k), (tile_k, 1))

    for ks in range(k_wmma_steps):
        k_step = arith.index(ks * WMMA_K)

        # Load B fragments
        b_frags = []
        if b_is_vec:
            # B is pre-loaded register vector (dot_op opIdx=1 layout)
            # Layout: [wn * (k_wmma_steps * 16) + ks * 16 + 0..15]
            for wn in range(wmma_n_rep):
                b_start = wn * (k_wmma_steps * 16) + ks * 16
                b_vals = []
                for j in range(16):
                    b_vals.append(_vec_dialect.extract(b_raw, [], [b_start + j]))
                b_frags.append(vector.from_elements(b_frag_type, b_vals))
        else:
            # B is LDS memref — load per-element with crd2idx addressing
            for wn in range(wmma_n_rep):
                n_off = warp_n_off + arith.index(wn * WMMA_N)
                vals = []
                for k0 in range(2):
                    for k1 in range(8):
                        kk = k_step + (arith.index(k0 * 2) + lane_kgrp) * arith.index(8) + arith.index(k1)
                        if b_transposed:
                            off = _crd2idx((n_off + lane16, kk), layout_lds_b)
                        else:
                            off = _crd2idx((kk, n_off + lane16), layout_lds_b)
                        if _b_sub_off is not None:
                            off = off + arith.index_cast(T.index, _b_sub_off)
                        val = _mr_d.load(b_lds_flat, [off])
                        vals.append(val)
                b_frags.append(vector.from_elements(b_frag_type, vals))

        # For each M-tile, extract A fragment and call WMMA
        for wm in range(wmma_m_rep):
            if a_is_vec:
                # A is in flat register vector (dot_op opIdx=0 layout)
                # Register layout: [m_tile_local * (k_wmma_steps * 16) + ks * 16 + 0..15]
                a_start = wm * (k_wmma_steps * 16) + ks * 16
                a_vals = []
                for j in range(16):
                    a_vals.append(_vec_dialect.extract(a_v, [], [a_start + j]))
                a_frag = vector.from_elements(a_frag_type, a_vals)
            else:
                # A is also in LDS — use crd2idx with warp M offset
                a_vals = []
                m_off = warp_m_off + arith.index(wm * WMMA_M)
                for k0 in range(2):
                    for k1 in range(8):
                        kk = k_step + (arith.index(k0 * 2) + lane_kgrp) * arith.index(8) + arith.index(k1)
                        off = _crd2idx((m_off + lane16, kk), layout_lds_a)
                        if _a_sub_off is not None:
                            off = off + arith.index_cast(T.index, _a_sub_off)
                        a_vals.append(_mr_d.load(a_v, [off]))
                a_frag = vector.from_elements(a_frag_type, a_vals)

            for wn in range(wmma_n_rep):
                acc_idx = wm * wmma_n_rep + wn
                accs[acc_idx] = wmma_op(
                    wmma_result_type,
                    b_frags[wn],
                    a_frag,
                    accs[acc_idx],
                    signA=False, signB=False, modC=0,
                    reuseA=False, reuseB=False,
                ).result

    # Pack accumulators back into a flat result vector
    result = c_v
    for i in range(n_accs):
        for j in range(c_per_wmma):
            elem = _vec_dialect.extract(accs[i], [], [j])
            result = _vec_dialect.insert(elem, result, [], [i * c_per_wmma + j])

    return result


def _crd2idx(crd, layout):
    """CuTE crd2idx: (coord_or_index, layout) → index-typed scalar offset.

    Accepts a scalar i32 (auto-converts to int_tuple) or a tuple coordinate.
    """
    # Auto-convert scalar i32 to int_tuple for fx.crd2idx
    if isinstance(crd, ir.Value) and not str(crd.type).startswith("!fly.int_tuple"):
        crd_i32 = crd
        if str(crd.type) != "i32":
            crd_i32 = std_arith.IndexCastOp(ir.IntegerType.get_signless(32), crd).result
        IntTupleTy, dyncElems = _fly_d.infer_int_tuple_type(crd_i32)
        crd = _fly_d.make_int_tuple(IntTupleTy, dyncElems)
    result = fx.crd2idx(crd, layout)
    scalar = fx.get_scalar(result)
    if isinstance(scalar, ir.Value) and not isinstance(scalar.type, ir.IndexType):
        scalar = std_arith.IndexCastOp(ir.IndexType.get(), scalar).result
    return scalar


def _idx2crd(idx, layout):
    """CuTE idx2crd: (linear_index, layout) → coordinate tuple.

    Returns the raw fly.int_tuple; use fx.get(result, i) to extract mode i.
    """
    if isinstance(idx, ir.Value) and not str(idx.type).startswith("!fly.int_tuple"):
        idx_i32 = idx
        if str(idx.type) != "i32":
            idx_i32 = std_arith.IndexCastOp(ir.IntegerType.get_signless(32), idx).result
        IntTupleTy, dyncElems = _fly_d.infer_int_tuple_type(idx_i32)
        idx = _fly_d.make_int_tuple(IntTupleTy, dyncElems)
    return fx.idx2crd(idx, layout)


def _make_reg_offset_vec(base, reg_shape, reg_stride):
    """Build vector<n x i32> of register offsets from CuTE layout pattern.

    offset[i] = base + crd2idx(i, make_layout(reg_shape, reg_stride))

    Example: _make_reg_offset_vec(base, (8, 8), (1, 16))
    → vector<64 x i32> with [base, base+1, ..., base+7, base+16, ..., base+119]
    """
    n = 1
    for s in reg_shape:
        n *= s

    def _flat_offset(i):
        off = 0
        for s, d in zip(reg_shape, reg_stride):
            off += (i % s) * d
            i //= s
        return off

    elems = []
    for i in range(n):
        o = _flat_offset(i)
        elems.append(base + o if o != 0 else base)
    return vector.from_elements(T.vec(n, T.i32), elems)


def _shuffle_repeat_each(src, n_repeat):
    """Repeat each element n_repeat times: [a,b,...] → [a,a,..., b,b,..., ...]"""
    from flydsl._mlir.dialects import vector as _vec_dialect
    sv = src.ir_value() if hasattr(src, "ir_value") else src
    n = sv.type.shape[0]
    mask = []
    for i in range(n):
        mask.extend([i] * n_repeat)
    return _vec_dialect.shuffle(src, src, mask)


def _shuffle_repeat_block(src, n_repeat):
    """Repeat entire vector n_repeat times: [a,b,c] → [a,b,c, a,b,c, ...]"""
    from flydsl._mlir.dialects import vector as _vec_dialect
    sv = src.ir_value() if hasattr(src, "ir_value") else src
    n = sv.type.shape[0]
    mask = list(range(n)) * n_repeat
    return _vec_dialect.shuffle(src, src, mask)


def _shuffle_select_repeat(src, indices, n_repeat):
    """Select elements at given indices, repeat each n_repeat times.

    Example: _shuffle_select_repeat(v, [0, 16], n_repeat=64)
    → [v[0],v[0],...(64×), v[16],v[16],...(64×)]
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    mask = []
    for idx in indices:
        mask.extend([idx] * n_repeat)
    return _vec_dialect.shuffle(src, src, mask)


def _buffer_load_dot_op_a(memref_ptr, offsets, masks, n_elems, elem_dtype,
                           tile_m=128, tile_k=128, warps_m=4, warps_n=1,
                           stride_m=128, WMMA_M=16, WMMA_N=16, WMMA_K=32):
    """Load A operand (Q) from global memory with dot_op opIdx=0 layout.

    The Triton dot_op<opIdx=0> encoding distributes the 128x128 A tile
    across threads according to the WMMA A-operand layout.
    Each thread loads 128 elements covering specific (M, K) positions.

    offsets is a per-element vector pre-computed by the MLIR lowering:
      offsets[flat_idx] = batch_head_off + M(flat_idx) * stride_m + K(flat_idx)
    where M and K follow the WMMA A-input linear layout (wm*64 + wave_id*16 + lane16).
    We use offsets[flat_idx] directly rather than recomputing M and K.
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    rsrc = buffer_ops.create_buffer_resource(memref_ptr)
    elem_ir = elem_dtype() if callable(elem_dtype) else elem_dtype

    warp_tile_m = tile_m // warps_m
    k_wmma_steps = tile_k // WMMA_K
    wmma_m_rep = warp_tile_m // WMMA_M

    # Build result vector
    if isinstance(elem_ir, ir.FloatType):
        zero_attr = ir.FloatAttr.get(elem_ir, 0.0)
    else:
        zero_attr = ir.IntegerAttr.get(elem_ir, 0)
    zero_elem = std_arith.ConstantOp(elem_ir, zero_attr).result
    result_type = ir.VectorType.get([n_elems], elem_ir)
    result_vec = _vec_dialect.broadcast(result_type, zero_elem)

    for wm in range(wmma_m_rep):
        for ks in range(k_wmma_steps):
            for j in range(16):
                flat_idx = wm * (k_wmma_steps * 16) + ks * 16 + j
                # Use pre-computed per-element offset from MLIR (already encodes M and K)
                off = _vec_dialect.extract(offsets, [], [flat_idx])
                # Apply per-element mask
                mask_i = None
                if masks is not None:
                    mask_i = _vec_dialect.extract(masks, [], [flat_idx])
                val_i = buffer_ops.buffer_load(rsrc, off, vec_width=1, dtype=elem_ir, mask=mask_i)
                result_vec = _vec_dialect.insert(val_i, result_vec, [], [flat_idx])

    return result_vec


def _buffer_store_vec(data_vec, memref_ptr, offsets, masks, n_elems, elem_dtype):
    """Emulate amdg.buffer_store (warp-collective vector store) via per-element buffer_store.

    Args:
        data_vec: vector<NxType> data to store
        memref_ptr: memref value (global memory tensor pointer)
        offsets: vector<NxI32> of per-element offsets (in elements)
        masks: vector<NxI1> of per-element masks (or None)
        n_elems: number of elements in the result vector
        elem_dtype: element FlyDSL type class (e.g. T.bf16, T.f32)
    """
    from flydsl._mlir.dialects import vector as _vec_dialect
    from flydsl._mlir.dialects import scf as _scf_d
    rsrc = buffer_ops.create_buffer_resource(memref_ptr)
    for i in range(n_elems):
        val_i = _vec_dialect.extract(data_vec, [], [i])
        off_i = _vec_dialect.extract(offsets, [], [i])
        if masks is not None:
            mask_i = _vec_dialect.extract(masks, [], [i])
            # Use scf.if for conditional store: avoids the broken sentinel-offset
            # approach (buffer_store mask=... sets offset=0x7FFFFFFF which is
            # still in-bounds for an unbounded buffer and causes SIGSEGV).
            if_op = _scf_d.IfOp(mask_i, [], has_else=False)
            with ir.InsertionPoint(if_op.then_block):
                buffer_ops.buffer_store(val_i, rsrc, off_i)
                _scf_d.YieldOp([])
        else:
            buffer_ops.buffer_store(val_i, rsrc, off_i)



# SmemAllocator: total LDS = 90048 bytes
_lds_allocator = SmemAllocator(None, arch="gfx1250", global_sym_name="kernel_smem")
_lds_allocator.ptr = 90048

_LDS_OFFSET__v38 = 0  # byte offset
_LDS_ELEMS__v38 = 17400  # total elements
_LDS_OFFSET__v41 = 34800  # byte offset
_LDS_ELEMS__v41 = 9208  # total elements
_LDS_OFFSET__v48 = 53216  # byte offset
_LDS_ELEMS__v48 = 18416  # total elements

@flyc.kernel
def mla_attn_fwd_pipelined_kernel(q_ptr: fx.Tensor, k_ptr: fx.Tensor, v_ptr: fx.Tensor, out_ptr: fx.Tensor, stride_qz: fx.Int32, stride_qh: fx.Int32, stride_qm: fx.Int32, stride_kz: fx.Int32, stride_kh: fx.Int32, stride_kn: fx.Int32, stride_vz: fx.Int32, stride_vh: fx.Int32, stride_vn: fx.Int32, stride_oz: fx.Int32, stride_oh: fx.Int32, stride_om: fx.Int32):
    stride_qz = stride_qz.ir_value()
    stride_qh = stride_qh.ir_value()
    stride_qm = stride_qm.ir_value()
    stride_kz = stride_kz.ir_value()
    stride_kh = stride_kh.ir_value()
    stride_kn = stride_kn.ir_value()
    stride_vz = stride_vz.ir_value()
    stride_vh = stride_vh.ir_value()
    stride_vn = stride_vn.ir_value()
    stride_oz = stride_oz.ir_value()
    stride_oh = stride_oh.ir_value()
    stride_om = stride_om.ir_value()
    
    # Get LDS base memref from SmemAllocator
    _lds_base = _lds_allocator.get_base()
    
    ONES_16 = arith.constant_vector(1.0, T.vec(16, T.f32))
    c2_i32 = arith.constant(2, type=T.i32)
    c192_i32 = arith.constant(192, type=T.i32)
    cst_0 = arith.constant_vector(0.10411755, T.vec(64, T.f32))
    cst_1 = arith.constant_vector(0.10411755, T.vec(2, T.f32))
    NEG_INF_64 = arith.constant_vector(float('-inf'), T.vec(64, T.f32))
    cst_3 = arith.constant_vector(512, T.vec(32, T.i32))
    ZEROS_64 = arith.constant_vector(0.0, T.vec(64, T.f32))
    c1_i32 = arith.constant(1, type=T.i32)
    c0_i32 = arith.constant(0, type=T.i32)
    c320_i32 = arith.constant(320, type=T.i32)
    ZEROS_128 = arith.constant_vector(0.0, T.vec(128, T.f32))
    ONES_2 = arith.constant_vector(1.0, T.vec(2, T.f32))
    NEG_INF_2 = arith.constant_vector(float('-inf'), T.vec(2, T.f32))
    cst_8 = arith.constant_vector(128, T.vec(16, T.i32))
    c64_i32 = arith.constant(64, type=T.i32)
    c1_i64 = arith.constant(1, type=T.i64)
    c512_i32 = arith.constant(512, type=T.i32)
    cst_9 = arith.constant_vector(128, T.vec(32, T.i32))
    cst_10 = arith.constant_vector(128, T.vec(32, T.i32))
    c128_i32 = arith.constant(128, type=T.i32)
    bid_x = arith.index_cast(T.i32, gpu.block_id("x"))
    bid_y = arith.index_cast(T.i32, gpu.block_id("y"))
    bid_z = arith.index_cast(T.i32, gpu.block_id("z"))
    _v3 = bid_z * c128_i32
    _v4 = stride_qz * bid_x
    _v5 = stride_qh * bid_y
    _v6 = _v4 + _v5
    thread_id_x = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x) if str(getattr(thread_id_x, "type", "")) != str(T.i32) else thread_id_x
    # _v8_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (1, 2, 4, 8, 0, 16, 32))
    _v8_base = (tid % 2) * 1 + ((tid // 2) % 2) * 2 + ((tid // 4) % 2) * 4 + ((tid // 8) % 2) * 8 + ((tid // 16) % 2) * 0 + ((tid // 32) % 2) * 16 + ((tid // 64) % 2) * 32
    _v8 = vector.from_elements(T.vec(2, T.i32), [_v8_base, _v8_base + 64])
    _v9 = vector.broadcast(T.vec(2, T.i32), _v3)
    _v10 = _v9 + _v8
    _v11 = _shuffle_repeat_each(_v10, n_repeat=16)
    _v12 = vector.broadcast(T.vec(32, T.i32), stride_qm)
    _v13 = _v12 * _v11
    _v14 = vector.broadcast(T.vec(32, T.i32), _v6)
    _v15 = _v14 + _v13
    thread_id_x_11 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_11) if str(getattr(thread_id_x_11, "type", "")) != str(T.i32) else thread_id_x_11
    # _v17_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (0, 0, 0, 0, 8, 0, 0))
    _v17_base = (tid % 2) * 0 + ((tid // 2) % 2) * 0 + ((tid // 4) % 2) * 0 + ((tid // 8) % 2) * 0 + ((tid // 16) % 2) * 8 + ((tid // 32) % 2) * 0 + ((tid // 64) % 2) * 0
    _v17 = _make_reg_offset_vec(_v17_base, (8, 8), (1, 16))
    _v18 = _shuffle_select_repeat(_v15, [0, 16], n_repeat=64)
    _v19 = _shuffle_repeat_block(_v17, n_repeat=2)
    _v20 = _v18 + _v19
    _v21 = _v11 < cst_10
    _v22 = _shuffle_select_repeat(_v21, [0, 16], n_repeat=64)
    _v23 = _buffer_load_dot_op_a(q_ptr, _v20, _v22, 128, T.bf16,
                                      tile_m=128, tile_k=128, warps_m=4, warps_n=1, stride_m=stride_qm)
    thread_id_x_12 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_12) if str(getattr(thread_id_x_12, "type", "")) != str(T.i32) else thread_id_x_12
    # _v25_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (0, 0, 0, 0, 8, 0, 0))
    _v25_base = (tid % 2) * 0 + ((tid // 2) % 2) * 0 + ((tid // 4) % 2) * 0 + ((tid // 8) % 2) * 0 + ((tid // 16) % 2) * 8 + ((tid // 32) % 2) * 0 + ((tid // 64) % 2) * 0
    _v25 = _make_reg_offset_vec(_v25_base, (8, 4), (1, 16))
    _v26 = _v25 + cst_9
    _v27 = _shuffle_select_repeat(_v15, [0, 16], n_repeat=32)
    _v28 = _shuffle_repeat_block(_v26, n_repeat=2)
    _v29 = _v27 + _v28
    _v30 = _shuffle_select_repeat(_v21, [0, 16], n_repeat=32)
    _v31 = _buffer_load_dot_op_a(q_ptr, _v29, _v30, 64, T.bf16,
                                      tile_m=128, tile_k=64, warps_m=4, warps_n=1, stride_m=stride_qm)
    _v32 = stride_kz * bid_x
    _v33 = _addptr(k_ptr, _v32, elem_bytes=2)  # addptr
    _v34 = stride_kh * bid_y
    _v35 = _addptr(_v33, _v34, elem_bytes=2)  # addptr
    _v36 = arith.extsi(T.i64, stride_kn)
    _v37 = _make_tdm_desc(_v35, [c512_i32, c128_i32], [_v36, c1_i64], elem_bytes=2, tile_shape=(64, 128), pad_interval=128, pad_amount=8, num_warps=1)
    _v38 = SmemPtr(_lds_base, _LDS_OFFSET__v38, T.bf16, shape=(_LDS_ELEMS__v38,)).get()  # LDS alloc via SmemAllocator
    _v39 = _addptr(_v35, c128_i32, elem_bytes=2)  # addptr
    _v40 = _make_tdm_desc(_v39, [c512_i32, c64_i32], [_v36, c1_i64], elem_bytes=2, tile_shape=(64, 64), pad_interval=64, pad_amount=8, num_warps=1)
    _v41 = SmemPtr(_lds_base, _LDS_OFFSET__v41, T.bf16, shape=(_LDS_ELEMS__v41,)).get()  # LDS alloc via SmemAllocator
    _v42 = stride_vz * bid_x
    _v43 = _addptr(v_ptr, _v42, elem_bytes=2)  # addptr
    _v44 = stride_vh * bid_y
    _v45 = _addptr(_v43, _v44, elem_bytes=2)  # addptr
    _v46 = arith.extsi(T.i64, stride_vn)
    _v47 = _make_tdm_desc(_v45, [c512_i32, c128_i32], [_v46, c1_i64], elem_bytes=2, tile_shape=(64, 128), pad_interval=128, pad_amount=16, num_warps=1)
    _v48 = SmemPtr(_lds_base, _LDS_OFFSET__v48, T.bf16, shape=(_LDS_ELEMS__v48,)).get()  # LDS alloc via SmemAllocator
    _v49 = stride_oz * bid_x
    _v50 = stride_oh * bid_y
    _v51 = _v49 + _v50
    thread_id_x_13 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_13) if str(getattr(thread_id_x_13, "type", "")) != str(T.i32) else thread_id_x_13
    # _v53_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (1, 2, 4, 8, 0, 16, 32))
    _v53_base = (tid % 2) * 1 + ((tid // 2) % 2) * 2 + ((tid // 4) % 2) * 4 + ((tid // 8) % 2) * 8 + ((tid // 16) % 2) * 0 + ((tid // 32) % 2) * 16 + ((tid // 64) % 2) * 32
    _v53 = vector.from_elements(T.vec(2, T.i32), [_v53_base, _v53_base + 64])
    _v54 = vector.broadcast(T.vec(2, T.i32), _v3)
    _v55 = _v54 + _v53
    _v56 = vector.shuffle(_v55, _v55, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v57 = vector.broadcast(T.vec(16, T.i32), stride_om)
    _v58 = _v57 * _v56
    _v59 = vector.broadcast(T.vec(16, T.i32), _v51)
    _v60 = _v59 + _v58
    thread_id_x_14 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_14) if str(getattr(thread_id_x_14, "type", "")) != str(T.i32) else thread_id_x_14
    # _v62_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (0, 0, 0, 0, 8, 0, 0))
    _v62_base = (tid % 2) * 0 + ((tid // 2) % 2) * 0 + ((tid // 4) % 2) * 0 + ((tid // 8) % 2) * 0 + ((tid // 16) % 2) * 8 + ((tid // 32) % 2) * 0 + ((tid // 64) % 2) * 0
    _v62 = _make_reg_offset_vec(_v62_base, (8, 8), (1, 16))
    _v63 = _shuffle_select_repeat(_v60, [0, 8], n_repeat=64)
    _v64 = _shuffle_repeat_block(_v62, n_repeat=2)
    _v65 = _v63 + _v64
    _v66 = _v56 < cst_8
    _v67 = _memdesc_index_subview(_v38, c0_i32, 8192, pad_interval=128, pad_amount=8)
    _v68 = _tdm_copy_to_lds(_v37, (c0_i32, c0_i32), _v67, elem_bytes=2)
    _v69 = _memdesc_index_subview(_v41, c0_i32, 4096, pad_interval=64, pad_amount=8)
    _v70 = _tdm_copy_to_lds(_v40, (c0_i32, c0_i32), _v69, elem_bytes=2)
    _v71 = _memdesc_index_subview(_v38, c1_i32, 8192, pad_interval=128, pad_amount=8)
    gpu.barrier()
    _v72 = _tdm_copy_to_lds(_v37, (c64_i32, c0_i32), _v71, elem_bytes=2)
    _v73 = _memdesc_index_subview(_v41, c1_i32, 4096, pad_interval=64, pad_amount=8)
    _v74 = _tdm_copy_to_lds(_v40, (c64_i32, c0_i32), _v73, elem_bytes=2)
    _v75 = _memdesc_index_subview(_v48, c0_i32, 8192, pad_interval=128, pad_amount=16)
    _v76 = _tdm_copy_to_lds(_v47, (c0_i32, c0_i32), _v75, elem_bytes=2)
    _v77 = tdm_ops.tensor_wait(3)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v78 = (_v67, True)  # memdesc_trans → (memref, transposed=True)
    # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
    _v79 = _lds_load_gf2(_v78, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 64, 65, 66, 67, 68, 69, 70, 71, 80, 81, 82, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 101, 102, 103, 112, 113, 114, 115, 116, 117, 118, 119, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 6144, 6145, 6146, 6147, 6148, 6149, 6150, 6151, 6160, 6161, 6162, 6163, 6164, 6165, 6166, 6167, 6176, 6177, 6178, 6179, 6180, 6181, 6182, 6183, 6192, 6193, 6194, 6195, 6196, 6197, 6198, 6199, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6256, 6257, 6258, 6259, 6260, 6261, 6262, 6263], [128, 256, 512, 1024, 8], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=8)
    _v80 = tdm_ops.tensor_wait(0)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v81 = (_v69, True)  # memdesc_trans → (memref, transposed=True)
    # fly.lds_load with pre-computed LinearLayout offsets (128 elements)
    _v82 = _lds_load_gf2(_v81, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127], [64, 128, 256, 512, 8], [0, 0], 128, T.bf16, pad_interval=64, pad_amount=8)
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v83 = _wmma_gemm_full(_v23, _v79, ZEROS_64, T.bf16, tile_m=128, tile_n=64, tile_k=128, warps_m=4, warps_n=1)
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v84 = _wmma_gemm_full(_v31, _v82, _v83, T.bf16, tile_m=128, tile_n=64, tile_k=64, warps_m=4, warps_n=1)
    thread_id_x_15 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_15) if str(getattr(thread_id_x_15, "type", "")) != str(T.i32) else thread_id_x_15
    # _v86_layout = fx.make_layout((2, 2, 2, 2, 2, 2, 2), (0, 0, 0, 0, 8, 0, 0))
    _v86_base = (tid % 2) * 0 + ((tid // 2) % 2) * 0 + ((tid // 4) % 2) * 0 + ((tid // 8) % 2) * 0 + ((tid // 16) % 2) * 8 + ((tid // 32) % 2) * 0 + ((tid // 64) % 2) * 0
    _v86 = _make_reg_offset_vec(_v86_base, (8, 4), (1, 16))
    _v87 = _v86 < cst_3
    _v88 = _shuffle_repeat_block(_v87, n_repeat=2)
    _v89 = arith.select(_v88, _v84, NEG_INF_64)
    ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
    _v90 = vector.extract(_v89, static_position=[0])
    c1 = arith.constant(1, type=T.index)
    c32 = arith.constant(32, type=T.index)
    c1_17 = arith.constant(1, type=T.index)
    _for_ctx__v91 = _SCFForCtx(c1, c32, c1_17, [_v90])
    with _for_ctx__v91 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c0_i32_102 = arith.constant(0, type=T.i32)
        _v359 = c0_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v89, _v359)
        _v361 = arith.maxnumf(arg17, _v360)
        _scf_yield_([_v361])
    _v91 = _for_ctx__v91.results[0]
    _v92 = vector.insert(_v91, ZEROS_2, static_position=[0], dynamic_position=[])
    _v93 = vector.extract(_v89, static_position=[32])
    c1_18 = arith.constant(1, type=T.index)
    c32_19 = arith.constant(32, type=T.index)
    c1_20 = arith.constant(1, type=T.index)
    _for_ctx__v94 = _SCFForCtx(c1_18, c32_19, c1_20, [_v93])
    with _for_ctx__v94 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c32_i32_102 = arith.constant(32, type=T.i32)
        _v359 = c32_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v89, _v359)
        _v361 = arith.maxnumf(arg17, _v360)
        _scf_yield_([_v361])
    _v94 = _for_ctx__v94.results[0]
    _v95 = vector.insert(_v94, _v92, static_position=[1], dynamic_position=[])
    _v96 = vector.extract(_v95, static_position=[0])
    thread_id_x_21 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_21) if str(getattr(thread_id_x_21, "type", "")) != str(T.i32) else thread_id_x_21
    c32_i32 = arith.constant(32, type=T.i32)
    _v98 = tid % c32_i32
    c16_i32 = arith.constant(16, type=T.i32)
    _v99 = _v98 ^ c16_i32
    c2_i32_22 = arith.constant(2, type=T.i32)
    _v100 = _v99 << c2_i32_22
    _v101 = arith.bitcast(T.i32, _v96)
    _v102 = rocdl.ds_bpermute(T.i32, _v100, _v101)
    _v103 = arith.bitcast(T.f32, _v102)
    _v104 = arith.maxnumf(_v96, _v103)
    _v105 = vector.insert(_v104, _v95, static_position=[0], dynamic_position=[])
    _v106 = vector.extract(_v105, static_position=[1])
    thread_id_x_23 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_23) if str(getattr(thread_id_x_23, "type", "")) != str(T.i32) else thread_id_x_23
    c32_i32_24 = arith.constant(32, type=T.i32)
    _v108 = tid % c32_i32_24
    c16_i32_25 = arith.constant(16, type=T.i32)
    _v109 = _v108 ^ c16_i32_25
    c2_i32_26 = arith.constant(2, type=T.i32)
    _v110 = _v109 << c2_i32_26
    _v111 = arith.bitcast(T.i32, _v106)
    _v112 = rocdl.ds_bpermute(T.i32, _v110, _v111)
    _v113 = arith.bitcast(T.f32, _v112)
    _v114 = arith.maxnumf(_v106, _v113)
    _v115 = vector.insert(_v114, _v105, static_position=[1], dynamic_position=[])
    _v116 = arith.maxnumf(_v115, NEG_INF_2)
    _v117 = _v116 * cst_1
    _v118 = _v89 * cst_0
    _v119 = vector.shuffle(_v117, _v117, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v120 = _shuffle_select_repeat(_v119, [0, 8], n_repeat=32)
    _v121 = _v118 - _v120
    _v122 = math_dialect.exp2(_v121)
    _v123 = NEG_INF_2 - _v117
    _v124 = math_dialect.exp2(_v123)
    _v125 = _memdesc_index_subview(_v48, c1_i32, 8192, pad_interval=128, pad_amount=16)
    _v126 = _tdm_copy_to_lds(_v47, (c64_i32, c0_i32), _v125, elem_bytes=2)
    _v127 = _tdm_copy_to_lds(_v37, (c128_i32, c0_i32), _v67, elem_bytes=2)
    gpu.barrier()
    _v128 = _tdm_copy_to_lds(_v40, (c128_i32, c0_i32), _v69, elem_bytes=2)
    _v129 = tdm_ops.tensor_wait(3)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v130 = (_v71, True)  # memdesc_trans → (memref, transposed=True)
    # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
    _v131 = _lds_load_gf2(_v130, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 64, 65, 66, 67, 68, 69, 70, 71, 80, 81, 82, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 101, 102, 103, 112, 113, 114, 115, 116, 117, 118, 119, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 6144, 6145, 6146, 6147, 6148, 6149, 6150, 6151, 6160, 6161, 6162, 6163, 6164, 6165, 6166, 6167, 6176, 6177, 6178, 6179, 6180, 6181, 6182, 6183, 6192, 6193, 6194, 6195, 6196, 6197, 6198, 6199, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6256, 6257, 6258, 6259, 6260, 6261, 6262, 6263], [128, 256, 512, 1024, 8], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=8)
    _v132 = tdm_ops.tensor_wait(0)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v133 = (_v73, True)  # memdesc_trans → (memref, transposed=True)
    # fly.lds_load with pre-computed LinearLayout offsets (128 elements)
    _v134 = _lds_load_gf2(_v133, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127], [64, 128, 256, 512, 8], [0, 0], 128, T.bf16, pad_interval=64, pad_amount=8)
    _for_ctx__v135_8 = _SCFForCtx(c0_i32, c320_i32, c64_i32, [_v116, ONES_2, ZEROS_128, _v131, _v134, _v122, _v124, c0_i32])
    with _for_ctx__v135_8 as (_iv_index, [arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arg16 + c128_i32
        _v359 = arg16 + c192_i32
        # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
        _v360 = _wmma_gemm_full(_v23, arg20, ZEROS_64, T.bf16, tile_m=128, tile_n=64, tile_k=128, warps_m=4, warps_n=1)
        # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
        _v361 = _wmma_gemm_full(_v31, arg21, _v360, T.bf16, tile_m=128, tile_n=64, tile_k=64, warps_m=4, warps_n=1)
        ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
        _v362 = vector.extract(arg22, static_position=[0])
        c1_103 = arith.constant(1, type=T.index)
        c32_104 = arith.constant(32, type=T.index)
        c1_105 = arith.constant(1, type=T.index)
        _for_ctx__v363 = _SCFForCtx(c1_103, c32_104, c1_105, [_v362])
        with _for_ctx__v363 as (_iv_index, [arg26]):
            arg25 = arith.index_cast(T.i32, _iv_index)
            _v453 = arith.index_cast(T.i32, arg25) if str(getattr(arg25, "type", "")) != str(T.i32) else arg25
            c0_i32_132 = arith.constant(0, type=T.i32)
            _v454 = c0_i32_132 + _v453
            _v455 = llvm_dialect.extractelement(arg22, _v454)
            _v456 = arg26 + _v455
            _scf_yield_([_v456])
        _v363 = _for_ctx__v363.results[0]
        _v364 = vector.insert(_v363, ZEROS_2, static_position=[0], dynamic_position=[])
        _v365 = vector.extract(arg22, static_position=[32])
        c1_106 = arith.constant(1, type=T.index)
        c32_107 = arith.constant(32, type=T.index)
        c1_108 = arith.constant(1, type=T.index)
        _for_ctx__v366 = _SCFForCtx(c1_106, c32_107, c1_108, [_v365])
        with _for_ctx__v366 as (_iv_index, [arg26]):
            arg25 = arith.index_cast(T.i32, _iv_index)
            _v453 = arith.index_cast(T.i32, arg25) if str(getattr(arg25, "type", "")) != str(T.i32) else arg25
            c32_i32_132 = arith.constant(32, type=T.i32)
            _v454 = c32_i32_132 + _v453
            _v455 = llvm_dialect.extractelement(arg22, _v454)
            _v456 = arg26 + _v455
            _scf_yield_([_v456])
        _v366 = _for_ctx__v366.results[0]
        _v367 = vector.insert(_v366, _v364, static_position=[1], dynamic_position=[])
        _v368 = vector.extract(_v367, static_position=[0])
        thread_id_x_109 = gpu.thread_id("x")
        tid = arith.index_cast(T.i32, thread_id_x_109) if str(getattr(thread_id_x_109, "type", "")) != str(T.i32) else thread_id_x_109
        c32_i32_110 = arith.constant(32, type=T.i32)
        _v370 = tid % c32_i32_110
        c16_i32_111 = arith.constant(16, type=T.i32)
        _v371 = _v370 ^ c16_i32_111
        c2_i32_112 = arith.constant(2, type=T.i32)
        _v372 = _v371 << c2_i32_112
        _v373 = arith.bitcast(T.i32, _v368)
        _v374 = rocdl.ds_bpermute(T.i32, _v372, _v373)
        _v375 = arith.bitcast(T.f32, _v374)
        _v376 = _v368 + _v375
        _v377 = vector.insert(_v376, _v367, static_position=[0], dynamic_position=[])
        _v378 = vector.extract(_v377, static_position=[1])
        thread_id_x_113 = gpu.thread_id("x")
        tid = arith.index_cast(T.i32, thread_id_x_113) if str(getattr(thread_id_x_113, "type", "")) != str(T.i32) else thread_id_x_113
        c32_i32_114 = arith.constant(32, type=T.i32)
        _v380 = tid % c32_i32_114
        c16_i32_115 = arith.constant(16, type=T.i32)
        _v381 = _v380 ^ c16_i32_115
        c2_i32_116 = arith.constant(2, type=T.i32)
        _v382 = _v381 << c2_i32_116
        _v383 = arith.bitcast(T.i32, _v378)
        _v384 = rocdl.ds_bpermute(T.i32, _v382, _v383)
        _v385 = arith.bitcast(T.f32, _v384)
        _v386 = _v378 + _v385
        _v387 = vector.insert(_v386, _v377, static_position=[1], dynamic_position=[])
        _v388 = vector.shuffle(arg23, arg23, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
        _v389 = _shuffle_select_repeat(_v388, [0, 8], n_repeat=64)
        _v390 = arg19 * _v389
        _v391 = arith.truncf(T.vec(64, T.bf16), arg22)
        _v392 = _v391  # unrealized_conversion_cast
        _v393 = arg18 * arg23
        _v394 = _v393 + _v387
        _v395 = arg24 % c2_i32
        _v396 = tdm_ops.tensor_wait(2)
        gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
        _v397 = _memdesc_index_subview(_v48, _v395, 8192, pad_interval=128, pad_amount=16)
        # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
        _v398 = _lds_load_gf2(_v397, [0, 128, 256, 384, 512, 640, 768, 896, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, 4096, 4224, 4352, 4480, 4608, 4736, 4864, 4992, 6144, 6272, 6400, 6528, 6656, 6784, 6912, 7040, 16, 144, 272, 400, 528, 656, 784, 912, 2064, 2192, 2320, 2448, 2576, 2704, 2832, 2960, 4112, 4240, 4368, 4496, 4624, 4752, 4880, 5008, 6160, 6288, 6416, 6544, 6672, 6800, 6928, 7056, 32, 160, 288, 416, 544, 672, 800, 928, 2080, 2208, 2336, 2464, 2592, 2720, 2848, 2976, 4128, 4256, 4384, 4512, 4640, 4768, 4896, 5024, 6176, 6304, 6432, 6560, 6688, 6816, 6944, 7072, 48, 176, 304, 432, 560, 688, 816, 944, 2096, 2224, 2352, 2480, 2608, 2736, 2864, 2992, 4144, 4272, 4400, 4528, 4656, 4784, 4912, 5040, 6192, 6320, 6448, 6576, 6704, 6832, 6960, 7088, 64, 192, 320, 448, 576, 704, 832, 960, 2112, 2240, 2368, 2496, 2624, 2752, 2880, 3008, 4160, 4288, 4416, 4544, 4672, 4800, 4928, 5056, 6208, 6336, 6464, 6592, 6720, 6848, 6976, 7104, 80, 208, 336, 464, 592, 720, 848, 976, 2128, 2256, 2384, 2512, 2640, 2768, 2896, 3024, 4176, 4304, 4432, 4560, 4688, 4816, 4944, 5072, 6224, 6352, 6480, 6608, 6736, 6864, 6992, 7120, 96, 224, 352, 480, 608, 736, 864, 992, 2144, 2272, 2400, 2528, 2656, 2784, 2912, 3040, 4192, 4320, 4448, 4576, 4704, 4832, 4960, 5088, 6240, 6368, 6496, 6624, 6752, 6880, 7008, 7136, 112, 240, 368, 496, 624, 752, 880, 1008, 2160, 2288, 2416, 2544, 2672, 2800, 2928, 3056, 4208, 4336, 4464, 4592, 4720, 4848, 4976, 5104, 6256, 6384, 6512, 6640, 6768, 6896, 7024, 7152], [1, 2, 4, 8, 1024], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=16)
        _v399 = arg24 + c1_i32
        _v400 = _v399 % c2_i32
        _v401 = _memdesc_index_subview(_v38, _v400, 8192, pad_interval=128, pad_amount=8)
        _v402 = _tdm_copy_to_lds(_v37, (_v359, c0_i32), _v401, elem_bytes=2)
        _v403 = _memdesc_index_subview(_v41, _v400, 4096, pad_interval=64, pad_amount=8)
        _v404 = _tdm_copy_to_lds(_v40, (_v359, c0_i32), _v403, elem_bytes=2)
        _v405 = _v392  # ttg.convert_layout #mma→dot_op (identity)
        _v406 = _v405  # unrealized_conversion_cast
        # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
        _v407 = _wmma_gemm_full(_v406, _v398, _v390, T.bf16, tile_m=128, tile_n=128, tile_k=64, warps_m=4, warps_n=1)
        ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
        _v408 = vector.extract(_v361, static_position=[0])
        c1_118 = arith.constant(1, type=T.index)
        c32_119 = arith.constant(32, type=T.index)
        c1_120 = arith.constant(1, type=T.index)
        _for_ctx__v409 = _SCFForCtx(c1_118, c32_119, c1_120, [_v408])
        with _for_ctx__v409 as (_iv_index, [arg26]):
            arg25 = arith.index_cast(T.i32, _iv_index)
            _v453 = arith.index_cast(T.i32, arg25) if str(getattr(arg25, "type", "")) != str(T.i32) else arg25
            c0_i32_132 = arith.constant(0, type=T.i32)
            _v454 = c0_i32_132 + _v453
            _v455 = llvm_dialect.extractelement(_v361, _v454)
            _v456 = arith.maxnumf(arg26, _v455)
            _scf_yield_([_v456])
        _v409 = _for_ctx__v409.results[0]
        _v410 = vector.insert(_v409, ZEROS_2, static_position=[0], dynamic_position=[])
        _v411 = vector.extract(_v361, static_position=[32])
        c1_121 = arith.constant(1, type=T.index)
        c32_122 = arith.constant(32, type=T.index)
        c1_123 = arith.constant(1, type=T.index)
        _for_ctx__v412 = _SCFForCtx(c1_121, c32_122, c1_123, [_v411])
        with _for_ctx__v412 as (_iv_index, [arg26]):
            arg25 = arith.index_cast(T.i32, _iv_index)
            _v453 = arith.index_cast(T.i32, arg25) if str(getattr(arg25, "type", "")) != str(T.i32) else arg25
            c32_i32_132 = arith.constant(32, type=T.i32)
            _v454 = c32_i32_132 + _v453
            _v455 = llvm_dialect.extractelement(_v361, _v454)
            _v456 = arith.maxnumf(arg26, _v455)
            _scf_yield_([_v456])
        _v412 = _for_ctx__v412.results[0]
        _v413 = vector.insert(_v412, _v410, static_position=[1], dynamic_position=[])
        _v414 = vector.extract(_v413, static_position=[0])
        thread_id_x_124 = gpu.thread_id("x")
        tid = arith.index_cast(T.i32, thread_id_x_124) if str(getattr(thread_id_x_124, "type", "")) != str(T.i32) else thread_id_x_124
        c32_i32_125 = arith.constant(32, type=T.i32)
        _v416 = tid % c32_i32_125
        c16_i32_126 = arith.constant(16, type=T.i32)
        _v417 = _v416 ^ c16_i32_126
        c2_i32_127 = arith.constant(2, type=T.i32)
        _v418 = _v417 << c2_i32_127
        _v419 = arith.bitcast(T.i32, _v414)
        _v420 = rocdl.ds_bpermute(T.i32, _v418, _v419)
        _v421 = arith.bitcast(T.f32, _v420)
        _v422 = arith.maxnumf(_v414, _v421)
        _v423 = vector.insert(_v422, _v413, static_position=[0], dynamic_position=[])
        _v424 = vector.extract(_v423, static_position=[1])
        thread_id_x_128 = gpu.thread_id("x")
        tid = arith.index_cast(T.i32, thread_id_x_128) if str(getattr(thread_id_x_128, "type", "")) != str(T.i32) else thread_id_x_128
        c32_i32_129 = arith.constant(32, type=T.i32)
        _v426 = tid % c32_i32_129
        c16_i32_130 = arith.constant(16, type=T.i32)
        _v427 = _v426 ^ c16_i32_130
        c2_i32_131 = arith.constant(2, type=T.i32)
        _v428 = _v427 << c2_i32_131
        _v429 = arith.bitcast(T.i32, _v424)
        _v430 = rocdl.ds_bpermute(T.i32, _v428, _v429)
        _v431 = arith.bitcast(T.f32, _v430)
        _v432 = arith.maxnumf(_v424, _v431)
        _v433 = vector.insert(_v432, _v423, static_position=[1], dynamic_position=[])
        _v434 = arith.maxnumf(arg17, _v433)
        _v435 = _v434 * cst_1
        _v436 = _v361 * cst_0
        _v437 = vector.shuffle(_v435, _v435, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
        _v438 = _shuffle_select_repeat(_v437, [0, 8], n_repeat=32)
        _v439 = _v436 - _v438
        _v440 = math_dialect.exp2(_v439)
        _v441 = arg17 * cst_1
        _v442 = _v441 - _v435
        _v443 = math_dialect.exp2(_v442)
        _v444 = tdm_ops.tensor_wait(2)
        gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
        _v445 = _memdesc_index_subview(_v38, _v395, 8192, pad_interval=128, pad_amount=8)
        _v446 = (_v445, True)  # memdesc_trans → (memref, transposed=True)
        # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
        _v447 = _lds_load_gf2(_v446, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 64, 65, 66, 67, 68, 69, 70, 71, 80, 81, 82, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 101, 102, 103, 112, 113, 114, 115, 116, 117, 118, 119, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 6144, 6145, 6146, 6147, 6148, 6149, 6150, 6151, 6160, 6161, 6162, 6163, 6164, 6165, 6166, 6167, 6176, 6177, 6178, 6179, 6180, 6181, 6182, 6183, 6192, 6193, 6194, 6195, 6196, 6197, 6198, 6199, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6256, 6257, 6258, 6259, 6260, 6261, 6262, 6263], [128, 256, 512, 1024, 8], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=8)
        _v448 = tdm_ops.tensor_wait(0)
        gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
        _v449 = _memdesc_index_subview(_v41, _v395, 4096, pad_interval=64, pad_amount=8)
        _v450 = (_v449, True)  # memdesc_trans → (memref, transposed=True)
        # fly.lds_load with pre-computed LinearLayout offsets (128 elements)
        _v451 = _lds_load_gf2(_v450, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127], [64, 128, 256, 512, 8], [0, 0], 128, T.bf16, pad_interval=64, pad_amount=8)
        _v452 = _tdm_copy_to_lds(_v47, (_v358, c0_i32), _v397, elem_bytes=2)
        _scf_yield_([_v434, _v394, _v407, _v447, _v451, _v440, _v443, _v399])
    _v135_r0 = _for_ctx__v135_8.results[0]
    _v135_r1 = _for_ctx__v135_8.results[1]
    _v135_r2 = _for_ctx__v135_8.results[2]
    _v135_r3 = _for_ctx__v135_8.results[3]
    _v135_r4 = _for_ctx__v135_8.results[4]
    _v135_r5 = _for_ctx__v135_8.results[5]
    _v135_r6 = _for_ctx__v135_8.results[6]
    _v135_r7 = _for_ctx__v135_8.results[7]
    _v136 = _v135_r7 - c1_i32
    _v137 = _v136 * c64_i32
    _v138 = _v137 + c128_i32
    _v139 = _v137 + c192_i32
    ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
    _v140 = vector.extract(_v135_r5, static_position=[0])
    c1_28 = arith.constant(1, type=T.index)
    c32_29 = arith.constant(32, type=T.index)
    c1_30 = arith.constant(1, type=T.index)
    _for_ctx__v141 = _SCFForCtx(c1_28, c32_29, c1_30, [_v140])
    with _for_ctx__v141 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c0_i32_102 = arith.constant(0, type=T.i32)
        _v359 = c0_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v135_r5, _v359)
        _v361 = arg17 + _v360
        _scf_yield_([_v361])
    _v141 = _for_ctx__v141.results[0]
    _v142 = vector.insert(_v141, ZEROS_2, static_position=[0], dynamic_position=[])
    _v143 = vector.extract(_v135_r5, static_position=[32])
    c1_31 = arith.constant(1, type=T.index)
    c32_32 = arith.constant(32, type=T.index)
    c1_33 = arith.constant(1, type=T.index)
    _for_ctx__v144 = _SCFForCtx(c1_31, c32_32, c1_33, [_v143])
    with _for_ctx__v144 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c32_i32_102 = arith.constant(32, type=T.i32)
        _v359 = c32_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v135_r5, _v359)
        _v361 = arg17 + _v360
        _scf_yield_([_v361])
    _v144 = _for_ctx__v144.results[0]
    _v145 = vector.insert(_v144, _v142, static_position=[1], dynamic_position=[])
    _v146 = vector.extract(_v145, static_position=[0])
    thread_id_x_34 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_34) if str(getattr(thread_id_x_34, "type", "")) != str(T.i32) else thread_id_x_34
    c32_i32_35 = arith.constant(32, type=T.i32)
    _v148 = tid % c32_i32_35
    c16_i32_36 = arith.constant(16, type=T.i32)
    _v149 = _v148 ^ c16_i32_36
    c2_i32_37 = arith.constant(2, type=T.i32)
    _v150 = _v149 << c2_i32_37
    _v151 = arith.bitcast(T.i32, _v146)
    _v152 = rocdl.ds_bpermute(T.i32, _v150, _v151)
    _v153 = arith.bitcast(T.f32, _v152)
    _v154 = _v146 + _v153
    _v155 = vector.insert(_v154, _v145, static_position=[0], dynamic_position=[])
    _v156 = vector.extract(_v155, static_position=[1])
    thread_id_x_38 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_38) if str(getattr(thread_id_x_38, "type", "")) != str(T.i32) else thread_id_x_38
    c32_i32_39 = arith.constant(32, type=T.i32)
    _v158 = tid % c32_i32_39
    c16_i32_40 = arith.constant(16, type=T.i32)
    _v159 = _v158 ^ c16_i32_40
    c2_i32_41 = arith.constant(2, type=T.i32)
    _v160 = _v159 << c2_i32_41
    _v161 = arith.bitcast(T.i32, _v156)
    _v162 = rocdl.ds_bpermute(T.i32, _v160, _v161)
    _v163 = arith.bitcast(T.f32, _v162)
    _v164 = _v156 + _v163
    _v165 = vector.insert(_v164, _v155, static_position=[1], dynamic_position=[])
    _v166 = vector.shuffle(_v135_r6, _v135_r6, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v167 = _shuffle_select_repeat(_v166, [0, 8], n_repeat=64)
    _v168 = _v135_r2 * _v167
    _v169 = arith.truncf(T.vec(64, T.bf16), _v135_r5)
    _v170 = _v169  # unrealized_conversion_cast
    _v171 = _v135_r1 * _v135_r6
    _v172 = _v171 + _v165
    _v173 = _v135_r7 % c2_i32
    _v174 = tdm_ops.tensor_wait(2)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v175 = _memdesc_index_subview(_v48, _v173, 8192, pad_interval=128, pad_amount=16)
    # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
    _v176 = _lds_load_gf2(_v175, [0, 128, 256, 384, 512, 640, 768, 896, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, 4096, 4224, 4352, 4480, 4608, 4736, 4864, 4992, 6144, 6272, 6400, 6528, 6656, 6784, 6912, 7040, 16, 144, 272, 400, 528, 656, 784, 912, 2064, 2192, 2320, 2448, 2576, 2704, 2832, 2960, 4112, 4240, 4368, 4496, 4624, 4752, 4880, 5008, 6160, 6288, 6416, 6544, 6672, 6800, 6928, 7056, 32, 160, 288, 416, 544, 672, 800, 928, 2080, 2208, 2336, 2464, 2592, 2720, 2848, 2976, 4128, 4256, 4384, 4512, 4640, 4768, 4896, 5024, 6176, 6304, 6432, 6560, 6688, 6816, 6944, 7072, 48, 176, 304, 432, 560, 688, 816, 944, 2096, 2224, 2352, 2480, 2608, 2736, 2864, 2992, 4144, 4272, 4400, 4528, 4656, 4784, 4912, 5040, 6192, 6320, 6448, 6576, 6704, 6832, 6960, 7088, 64, 192, 320, 448, 576, 704, 832, 960, 2112, 2240, 2368, 2496, 2624, 2752, 2880, 3008, 4160, 4288, 4416, 4544, 4672, 4800, 4928, 5056, 6208, 6336, 6464, 6592, 6720, 6848, 6976, 7104, 80, 208, 336, 464, 592, 720, 848, 976, 2128, 2256, 2384, 2512, 2640, 2768, 2896, 3024, 4176, 4304, 4432, 4560, 4688, 4816, 4944, 5072, 6224, 6352, 6480, 6608, 6736, 6864, 6992, 7120, 96, 224, 352, 480, 608, 736, 864, 992, 2144, 2272, 2400, 2528, 2656, 2784, 2912, 3040, 4192, 4320, 4448, 4576, 4704, 4832, 4960, 5088, 6240, 6368, 6496, 6624, 6752, 6880, 7008, 7136, 112, 240, 368, 496, 624, 752, 880, 1008, 2160, 2288, 2416, 2544, 2672, 2800, 2928, 3056, 4208, 4336, 4464, 4592, 4720, 4848, 4976, 5104, 6256, 6384, 6512, 6640, 6768, 6896, 7024, 7152], [1, 2, 4, 8, 1024], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=16)
    _v177 = _v170  # ttg.convert_layout #mma→dot_op (identity)
    _v178 = _v177  # unrealized_conversion_cast
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v179 = _wmma_gemm_full(_v178, _v176, _v168, T.bf16, tile_m=128, tile_n=128, tile_k=64, warps_m=4, warps_n=1)
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v180 = _wmma_gemm_full(_v23, _v135_r3, ZEROS_64, T.bf16, tile_m=128, tile_n=64, tile_k=128, warps_m=4, warps_n=1)
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v181 = _wmma_gemm_full(_v31, _v135_r4, _v180, T.bf16, tile_m=128, tile_n=64, tile_k=64, warps_m=4, warps_n=1)
    _v182 = vector.broadcast(T.vec(32, T.i32), _v138)
    _v183 = _v182 + _v86
    _v184 = _v183 < cst_3
    _v185 = _shuffle_repeat_block(_v184, n_repeat=2)
    _v186 = arith.select(_v185, _v181, NEG_INF_64)
    ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
    _v187 = vector.extract(_v186, static_position=[0])
    c1_43 = arith.constant(1, type=T.index)
    c32_44 = arith.constant(32, type=T.index)
    c1_45 = arith.constant(1, type=T.index)
    _for_ctx__v188 = _SCFForCtx(c1_43, c32_44, c1_45, [_v187])
    with _for_ctx__v188 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c0_i32_102 = arith.constant(0, type=T.i32)
        _v359 = c0_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v186, _v359)
        _v361 = arith.maxnumf(arg17, _v360)
        _scf_yield_([_v361])
    _v188 = _for_ctx__v188.results[0]
    _v189 = vector.insert(_v188, ZEROS_2, static_position=[0], dynamic_position=[])
    _v190 = vector.extract(_v186, static_position=[32])
    c1_46 = arith.constant(1, type=T.index)
    c32_47 = arith.constant(32, type=T.index)
    c1_48 = arith.constant(1, type=T.index)
    _for_ctx__v191 = _SCFForCtx(c1_46, c32_47, c1_48, [_v190])
    with _for_ctx__v191 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c32_i32_102 = arith.constant(32, type=T.i32)
        _v359 = c32_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v186, _v359)
        _v361 = arith.maxnumf(arg17, _v360)
        _scf_yield_([_v361])
    _v191 = _for_ctx__v191.results[0]
    _v192 = vector.insert(_v191, _v189, static_position=[1], dynamic_position=[])
    _v193 = vector.extract(_v192, static_position=[0])
    thread_id_x_49 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_49) if str(getattr(thread_id_x_49, "type", "")) != str(T.i32) else thread_id_x_49
    c32_i32_50 = arith.constant(32, type=T.i32)
    _v195 = tid % c32_i32_50
    c16_i32_51 = arith.constant(16, type=T.i32)
    _v196 = _v195 ^ c16_i32_51
    c2_i32_52 = arith.constant(2, type=T.i32)
    _v197 = _v196 << c2_i32_52
    _v198 = arith.bitcast(T.i32, _v193)
    _v199 = rocdl.ds_bpermute(T.i32, _v197, _v198)
    _v200 = arith.bitcast(T.f32, _v199)
    _v201 = arith.maxnumf(_v193, _v200)
    _v202 = vector.insert(_v201, _v192, static_position=[0], dynamic_position=[])
    _v203 = vector.extract(_v202, static_position=[1])
    thread_id_x_53 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_53) if str(getattr(thread_id_x_53, "type", "")) != str(T.i32) else thread_id_x_53
    c32_i32_54 = arith.constant(32, type=T.i32)
    _v205 = tid % c32_i32_54
    c16_i32_55 = arith.constant(16, type=T.i32)
    _v206 = _v205 ^ c16_i32_55
    c2_i32_56 = arith.constant(2, type=T.i32)
    _v207 = _v206 << c2_i32_56
    _v208 = arith.bitcast(T.i32, _v203)
    _v209 = rocdl.ds_bpermute(T.i32, _v207, _v208)
    _v210 = arith.bitcast(T.f32, _v209)
    _v211 = arith.maxnumf(_v203, _v210)
    _v212 = vector.insert(_v211, _v202, static_position=[1], dynamic_position=[])
    _v213 = arith.maxnumf(_v135_r0, _v212)
    _v214 = _v213 * cst_1
    _v215 = _v186 * cst_0
    _v216 = vector.shuffle(_v214, _v214, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v217 = _shuffle_select_repeat(_v216, [0, 8], n_repeat=32)
    _v218 = _v215 - _v217
    _v219 = math_dialect.exp2(_v218)
    _v220 = _v135_r0 * cst_1
    _v221 = _v220 - _v214
    _v222 = math_dialect.exp2(_v221)
    _v223 = tdm_ops.tensor_wait(1)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v224 = _memdesc_index_subview(_v38, _v173, 8192, pad_interval=128, pad_amount=8)
    _v225 = (_v224, True)  # memdesc_trans → (memref, transposed=True)
    # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
    _v226 = _lds_load_gf2(_v225, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 64, 65, 66, 67, 68, 69, 70, 71, 80, 81, 82, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 101, 102, 103, 112, 113, 114, 115, 116, 117, 118, 119, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 6144, 6145, 6146, 6147, 6148, 6149, 6150, 6151, 6160, 6161, 6162, 6163, 6164, 6165, 6166, 6167, 6176, 6177, 6178, 6179, 6180, 6181, 6182, 6183, 6192, 6193, 6194, 6195, 6196, 6197, 6198, 6199, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6256, 6257, 6258, 6259, 6260, 6261, 6262, 6263], [128, 256, 512, 1024, 8], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=8)
    _v227 = tdm_ops.tensor_wait(0)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v228 = _memdesc_index_subview(_v41, _v173, 4096, pad_interval=64, pad_amount=8)
    _v229 = (_v228, True)  # memdesc_trans → (memref, transposed=True)
    # fly.lds_load with pre-computed LinearLayout offsets (128 elements)
    _v230 = _lds_load_gf2(_v229, [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127], [64, 128, 256, 512, 8], [0, 0], 128, T.bf16, pad_interval=64, pad_amount=8)
    _v231 = _tdm_copy_to_lds(_v47, (_v139, c0_i32), _v175, elem_bytes=2)
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v232 = _wmma_gemm_full(_v23, _v226, ZEROS_64, T.bf16, tile_m=128, tile_n=64, tile_k=128, warps_m=4, warps_n=1)
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v233 = _wmma_gemm_full(_v31, _v230, _v232, T.bf16, tile_m=128, tile_n=64, tile_k=64, warps_m=4, warps_n=1)
    _v234 = vector.broadcast(T.vec(32, T.i32), _v139)
    _v235 = _v234 + _v86
    _v236 = _v235 < cst_3
    _v237 = _shuffle_repeat_block(_v236, n_repeat=2)
    _v238 = arith.select(_v237, _v233, NEG_INF_64)
    ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
    _v239 = vector.extract(_v219, static_position=[0])
    c1_58 = arith.constant(1, type=T.index)
    c32_59 = arith.constant(32, type=T.index)
    c1_60 = arith.constant(1, type=T.index)
    _for_ctx__v240 = _SCFForCtx(c1_58, c32_59, c1_60, [_v239])
    with _for_ctx__v240 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c0_i32_102 = arith.constant(0, type=T.i32)
        _v359 = c0_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v219, _v359)
        _v361 = arg17 + _v360
        _scf_yield_([_v361])
    _v240 = _for_ctx__v240.results[0]
    _v241 = vector.insert(_v240, ZEROS_2, static_position=[0], dynamic_position=[])
    _v242 = vector.extract(_v219, static_position=[32])
    c1_61 = arith.constant(1, type=T.index)
    c32_62 = arith.constant(32, type=T.index)
    c1_63 = arith.constant(1, type=T.index)
    _for_ctx__v243 = _SCFForCtx(c1_61, c32_62, c1_63, [_v242])
    with _for_ctx__v243 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c32_i32_102 = arith.constant(32, type=T.i32)
        _v359 = c32_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v219, _v359)
        _v361 = arg17 + _v360
        _scf_yield_([_v361])
    _v243 = _for_ctx__v243.results[0]
    _v244 = vector.insert(_v243, _v241, static_position=[1], dynamic_position=[])
    _v245 = vector.extract(_v244, static_position=[0])
    thread_id_x_64 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_64) if str(getattr(thread_id_x_64, "type", "")) != str(T.i32) else thread_id_x_64
    c32_i32_65 = arith.constant(32, type=T.i32)
    _v247 = tid % c32_i32_65
    c16_i32_66 = arith.constant(16, type=T.i32)
    _v248 = _v247 ^ c16_i32_66
    c2_i32_67 = arith.constant(2, type=T.i32)
    _v249 = _v248 << c2_i32_67
    _v250 = arith.bitcast(T.i32, _v245)
    _v251 = rocdl.ds_bpermute(T.i32, _v249, _v250)
    _v252 = arith.bitcast(T.f32, _v251)
    _v253 = _v245 + _v252
    _v254 = vector.insert(_v253, _v244, static_position=[0], dynamic_position=[])
    _v255 = vector.extract(_v254, static_position=[1])
    thread_id_x_68 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_68) if str(getattr(thread_id_x_68, "type", "")) != str(T.i32) else thread_id_x_68
    c32_i32_69 = arith.constant(32, type=T.i32)
    _v257 = tid % c32_i32_69
    c16_i32_70 = arith.constant(16, type=T.i32)
    _v258 = _v257 ^ c16_i32_70
    c2_i32_71 = arith.constant(2, type=T.i32)
    _v259 = _v258 << c2_i32_71
    _v260 = arith.bitcast(T.i32, _v255)
    _v261 = rocdl.ds_bpermute(T.i32, _v259, _v260)
    _v262 = arith.bitcast(T.f32, _v261)
    _v263 = _v255 + _v262
    _v264 = vector.insert(_v263, _v254, static_position=[1], dynamic_position=[])
    _v265 = vector.shuffle(_v222, _v222, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v266 = _shuffle_select_repeat(_v265, [0, 8], n_repeat=64)
    _v267 = _v179 * _v266
    _v268 = arith.truncf(T.vec(64, T.bf16), _v219)
    _v269 = _v268  # unrealized_conversion_cast
    _v270 = _v172 * _v222
    _v271 = _v270 + _v264
    _v272 = _v135_r7 + c1_i32
    _v273 = _v272 % c2_i32
    _v274 = tdm_ops.tensor_wait(1)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    _v275 = _memdesc_index_subview(_v48, _v273, 8192, pad_interval=128, pad_amount=16)
    # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
    _v276 = _lds_load_gf2(_v275, [0, 128, 256, 384, 512, 640, 768, 896, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, 4096, 4224, 4352, 4480, 4608, 4736, 4864, 4992, 6144, 6272, 6400, 6528, 6656, 6784, 6912, 7040, 16, 144, 272, 400, 528, 656, 784, 912, 2064, 2192, 2320, 2448, 2576, 2704, 2832, 2960, 4112, 4240, 4368, 4496, 4624, 4752, 4880, 5008, 6160, 6288, 6416, 6544, 6672, 6800, 6928, 7056, 32, 160, 288, 416, 544, 672, 800, 928, 2080, 2208, 2336, 2464, 2592, 2720, 2848, 2976, 4128, 4256, 4384, 4512, 4640, 4768, 4896, 5024, 6176, 6304, 6432, 6560, 6688, 6816, 6944, 7072, 48, 176, 304, 432, 560, 688, 816, 944, 2096, 2224, 2352, 2480, 2608, 2736, 2864, 2992, 4144, 4272, 4400, 4528, 4656, 4784, 4912, 5040, 6192, 6320, 6448, 6576, 6704, 6832, 6960, 7088, 64, 192, 320, 448, 576, 704, 832, 960, 2112, 2240, 2368, 2496, 2624, 2752, 2880, 3008, 4160, 4288, 4416, 4544, 4672, 4800, 4928, 5056, 6208, 6336, 6464, 6592, 6720, 6848, 6976, 7104, 80, 208, 336, 464, 592, 720, 848, 976, 2128, 2256, 2384, 2512, 2640, 2768, 2896, 3024, 4176, 4304, 4432, 4560, 4688, 4816, 4944, 5072, 6224, 6352, 6480, 6608, 6736, 6864, 6992, 7120, 96, 224, 352, 480, 608, 736, 864, 992, 2144, 2272, 2400, 2528, 2656, 2784, 2912, 3040, 4192, 4320, 4448, 4576, 4704, 4832, 4960, 5088, 6240, 6368, 6496, 6624, 6752, 6880, 7008, 7136, 112, 240, 368, 496, 624, 752, 880, 1008, 2160, 2288, 2416, 2544, 2672, 2800, 2928, 3056, 4208, 4336, 4464, 4592, 4720, 4848, 4976, 5104, 6256, 6384, 6512, 6640, 6768, 6896, 7024, 7152], [1, 2, 4, 8, 1024], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=16)
    _v277 = _v269  # ttg.convert_layout #mma→dot_op (identity)
    _v278 = _v277  # unrealized_conversion_cast
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v279 = _wmma_gemm_full(_v278, _v276, _v267, T.bf16, tile_m=128, tile_n=128, tile_k=64, warps_m=4, warps_n=1)
    ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
    _v280 = vector.extract(_v238, static_position=[0])
    c1_73 = arith.constant(1, type=T.index)
    c32_74 = arith.constant(32, type=T.index)
    c1_75 = arith.constant(1, type=T.index)
    _for_ctx__v281 = _SCFForCtx(c1_73, c32_74, c1_75, [_v280])
    with _for_ctx__v281 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c0_i32_102 = arith.constant(0, type=T.i32)
        _v359 = c0_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v238, _v359)
        _v361 = arith.maxnumf(arg17, _v360)
        _scf_yield_([_v361])
    _v281 = _for_ctx__v281.results[0]
    _v282 = vector.insert(_v281, ZEROS_2, static_position=[0], dynamic_position=[])
    _v283 = vector.extract(_v238, static_position=[32])
    c1_76 = arith.constant(1, type=T.index)
    c32_77 = arith.constant(32, type=T.index)
    c1_78 = arith.constant(1, type=T.index)
    _for_ctx__v284 = _SCFForCtx(c1_76, c32_77, c1_78, [_v283])
    with _for_ctx__v284 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c32_i32_102 = arith.constant(32, type=T.i32)
        _v359 = c32_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v238, _v359)
        _v361 = arith.maxnumf(arg17, _v360)
        _scf_yield_([_v361])
    _v284 = _for_ctx__v284.results[0]
    _v285 = vector.insert(_v284, _v282, static_position=[1], dynamic_position=[])
    _v286 = vector.extract(_v285, static_position=[0])
    thread_id_x_79 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_79) if str(getattr(thread_id_x_79, "type", "")) != str(T.i32) else thread_id_x_79
    c32_i32_80 = arith.constant(32, type=T.i32)
    _v288 = tid % c32_i32_80
    c16_i32_81 = arith.constant(16, type=T.i32)
    _v289 = _v288 ^ c16_i32_81
    c2_i32_82 = arith.constant(2, type=T.i32)
    _v290 = _v289 << c2_i32_82
    _v291 = arith.bitcast(T.i32, _v286)
    _v292 = rocdl.ds_bpermute(T.i32, _v290, _v291)
    _v293 = arith.bitcast(T.f32, _v292)
    _v294 = arith.maxnumf(_v286, _v293)
    _v295 = vector.insert(_v294, _v285, static_position=[0], dynamic_position=[])
    _v296 = vector.extract(_v295, static_position=[1])
    thread_id_x_83 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_83) if str(getattr(thread_id_x_83, "type", "")) != str(T.i32) else thread_id_x_83
    c32_i32_84 = arith.constant(32, type=T.i32)
    _v298 = tid % c32_i32_84
    c16_i32_85 = arith.constant(16, type=T.i32)
    _v299 = _v298 ^ c16_i32_85
    c2_i32_86 = arith.constant(2, type=T.i32)
    _v300 = _v299 << c2_i32_86
    _v301 = arith.bitcast(T.i32, _v296)
    _v302 = rocdl.ds_bpermute(T.i32, _v300, _v301)
    _v303 = arith.bitcast(T.f32, _v302)
    _v304 = arith.maxnumf(_v296, _v303)
    _v305 = vector.insert(_v304, _v295, static_position=[1], dynamic_position=[])
    _v306 = arith.maxnumf(_v213, _v305)
    _v307 = _v306 * cst_1
    _v308 = _v238 * cst_0
    _v309 = vector.shuffle(_v307, _v307, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v310 = _shuffle_select_repeat(_v309, [0, 8], n_repeat=32)
    _v311 = _v308 - _v310
    _v312 = math_dialect.exp2(_v311)
    _v313 = _v214 - _v307
    _v314 = math_dialect.exp2(_v313)
    ZEROS_2 = arith.constant_vector(0.0, T.vec(2, T.f32))
    _v315 = vector.extract(_v312, static_position=[0])
    c1_88 = arith.constant(1, type=T.index)
    c32_89 = arith.constant(32, type=T.index)
    c1_90 = arith.constant(1, type=T.index)
    _for_ctx__v316 = _SCFForCtx(c1_88, c32_89, c1_90, [_v315])
    with _for_ctx__v316 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c0_i32_102 = arith.constant(0, type=T.i32)
        _v359 = c0_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v312, _v359)
        _v361 = arg17 + _v360
        _scf_yield_([_v361])
    _v316 = _for_ctx__v316.results[0]
    _v317 = vector.insert(_v316, ZEROS_2, static_position=[0], dynamic_position=[])
    _v318 = vector.extract(_v312, static_position=[32])
    c1_91 = arith.constant(1, type=T.index)
    c32_92 = arith.constant(32, type=T.index)
    c1_93 = arith.constant(1, type=T.index)
    _for_ctx__v319 = _SCFForCtx(c1_91, c32_92, c1_93, [_v318])
    with _for_ctx__v319 as (_iv_index, [arg17]):
        arg16 = arith.index_cast(T.i32, _iv_index)
        _v358 = arith.index_cast(T.i32, arg16) if str(getattr(arg16, "type", "")) != str(T.i32) else arg16
        c32_i32_102 = arith.constant(32, type=T.i32)
        _v359 = c32_i32_102 + _v358
        _v360 = llvm_dialect.extractelement(_v312, _v359)
        _v361 = arg17 + _v360
        _scf_yield_([_v361])
    _v319 = _for_ctx__v319.results[0]
    _v320 = vector.insert(_v319, _v317, static_position=[1], dynamic_position=[])
    _v321 = vector.extract(_v320, static_position=[0])
    thread_id_x_94 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_94) if str(getattr(thread_id_x_94, "type", "")) != str(T.i32) else thread_id_x_94
    c32_i32_95 = arith.constant(32, type=T.i32)
    _v323 = tid % c32_i32_95
    c16_i32_96 = arith.constant(16, type=T.i32)
    _v324 = _v323 ^ c16_i32_96
    c2_i32_97 = arith.constant(2, type=T.i32)
    _v325 = _v324 << c2_i32_97
    _v326 = arith.bitcast(T.i32, _v321)
    _v327 = rocdl.ds_bpermute(T.i32, _v325, _v326)
    _v328 = arith.bitcast(T.f32, _v327)
    _v329 = _v321 + _v328
    _v330 = vector.insert(_v329, _v320, static_position=[0], dynamic_position=[])
    _v331 = vector.extract(_v330, static_position=[1])
    thread_id_x_98 = gpu.thread_id("x")
    tid = arith.index_cast(T.i32, thread_id_x_98) if str(getattr(thread_id_x_98, "type", "")) != str(T.i32) else thread_id_x_98
    c32_i32_99 = arith.constant(32, type=T.i32)
    _v333 = tid % c32_i32_99
    c16_i32_100 = arith.constant(16, type=T.i32)
    _v334 = _v333 ^ c16_i32_100
    c2_i32_101 = arith.constant(2, type=T.i32)
    _v335 = _v334 << c2_i32_101
    _v336 = arith.bitcast(T.i32, _v331)
    _v337 = rocdl.ds_bpermute(T.i32, _v335, _v336)
    _v338 = arith.bitcast(T.f32, _v337)
    _v339 = _v331 + _v338
    _v340 = vector.insert(_v339, _v330, static_position=[1], dynamic_position=[])
    _v341 = vector.shuffle(_v314, _v314, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v342 = _shuffle_select_repeat(_v341, [0, 8], n_repeat=64)
    _v343 = _v279 * _v342
    _v344 = arith.truncf(T.vec(64, T.bf16), _v312)
    _v345 = _v344  # unrealized_conversion_cast
    _v346 = _v271 * _v314
    _v347 = _v346 + _v340
    _v348 = tdm_ops.tensor_wait(0)
    gpu.barrier()  # TDM is async; barrier ensures LDS visible to all waves
    # fly.lds_load with pre-computed LinearLayout offsets (256 elements)
    _v349 = _lds_load_gf2(_v175, [0, 128, 256, 384, 512, 640, 768, 896, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, 4096, 4224, 4352, 4480, 4608, 4736, 4864, 4992, 6144, 6272, 6400, 6528, 6656, 6784, 6912, 7040, 16, 144, 272, 400, 528, 656, 784, 912, 2064, 2192, 2320, 2448, 2576, 2704, 2832, 2960, 4112, 4240, 4368, 4496, 4624, 4752, 4880, 5008, 6160, 6288, 6416, 6544, 6672, 6800, 6928, 7056, 32, 160, 288, 416, 544, 672, 800, 928, 2080, 2208, 2336, 2464, 2592, 2720, 2848, 2976, 4128, 4256, 4384, 4512, 4640, 4768, 4896, 5024, 6176, 6304, 6432, 6560, 6688, 6816, 6944, 7072, 48, 176, 304, 432, 560, 688, 816, 944, 2096, 2224, 2352, 2480, 2608, 2736, 2864, 2992, 4144, 4272, 4400, 4528, 4656, 4784, 4912, 5040, 6192, 6320, 6448, 6576, 6704, 6832, 6960, 7088, 64, 192, 320, 448, 576, 704, 832, 960, 2112, 2240, 2368, 2496, 2624, 2752, 2880, 3008, 4160, 4288, 4416, 4544, 4672, 4800, 4928, 5056, 6208, 6336, 6464, 6592, 6720, 6848, 6976, 7104, 80, 208, 336, 464, 592, 720, 848, 976, 2128, 2256, 2384, 2512, 2640, 2768, 2896, 3024, 4176, 4304, 4432, 4560, 4688, 4816, 4944, 5072, 6224, 6352, 6480, 6608, 6736, 6864, 6992, 7120, 96, 224, 352, 480, 608, 736, 864, 992, 2144, 2272, 2400, 2528, 2656, 2784, 2912, 3040, 4192, 4320, 4448, 4576, 4704, 4832, 4960, 5088, 6240, 6368, 6496, 6624, 6752, 6880, 7008, 7136, 112, 240, 368, 496, 624, 752, 880, 1008, 2160, 2288, 2416, 2544, 2672, 2800, 2928, 3056, 4208, 4336, 4464, 4592, 4720, 4848, 4976, 5104, 6256, 6384, 6512, 6640, 6768, 6896, 7024, 7152], [1, 2, 4, 8, 1024], [0, 0], 256, T.bf16, pad_interval=128, pad_amount=16)
    _v350 = _v345  # ttg.convert_layout #mma→dot_op (identity)
    _v351 = _v350  # unrealized_conversion_cast
    # GEMM: wmma_16x16x32 (16x16x32) — tiled WMMA, warps_m=4 warps_n=1
    _v352 = _wmma_gemm_full(_v351, _v349, _v343, T.bf16, tile_m=128, tile_n=128, tile_k=64, warps_m=4, warps_n=1)
    _v353 = vector.shuffle(_v347, _v347, [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])
    _v354 = ONES_16 / _v353
    _v355 = _shuffle_select_repeat(_v354, [0, 8], n_repeat=64)
    _v356 = _v352 * _v355
    _v357 = _shuffle_select_repeat(_v66, [0, 8], n_repeat=64)
    _buffer_store_vec(_v356, out_ptr, _v65, _v357, 128, T.f32)
    return
