# SPDX-License-Identifier: Apache-2.0
"""Compare DSV4-Pro fused and unfused GPU implementations against Torch.

Run from the FlyDSL root. ``torchrun --standalone --nproc-per-node=8 -m ...``
is required for --tp 8. Shape validation intentionally precedes GPU imports.
"""

import argparse
import json
import math
import os
import statistics
from pathlib import Path

from ..config import Dsv4Config, validate_shape


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--batch-size", type=int, default=1)
    p.add_argument("--seq-lens", type=int, nargs="+", default=[1, 2, 3, 4])
    p.add_argument("--tp", type=int, choices=(1, 2, 4, 8), default=1)
    p.add_argument("--routing", choices=("auto", "bias", "hash", "both"), default="auto")
    p.add_argument("--checkpoint", type=Path, help="native Pro checkpoint; synthetic weights otherwise")
    p.add_argument("--layer", type=int, default=3, help="backbone layer for --checkpoint (0..60)")
    p.add_argument(
        "--shared-format",
        choices=("fp8", "fp4"),
        default="fp8",
        help="native Pro uses FP8; FP4 is a synthetic fixture only",
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--replays", type=int, default=3, help="changed-input correctness replays")
    p.add_argument("--warmup", type=int, default=3)
    p.add_argument("--repeats", type=int, default=20)
    p.add_argument("--graph-iters", type=int, default=10)
    p.add_argument("--bench", action="store_true")
    p.add_argument("--atom-baseline", action="store_true", help="also compare ATOM's standard A8W4 operation path")
    p.add_argument("--atom-profile", choices=("default", "stable-rne"), default="default")
    p.add_argument("--atom-config-dir", type=Path, help="profile generated by tools.accuracy_config")
    p.add_argument(
        "--atom-module",
        action="store_true",
        help="exercise the real ATOM MoE module with mono enabled and disabled (requires checkpoint)",
    )
    p.add_argument(
        "--atom-samples",
        type=int,
        default=3,
        help="repeat the ATOM baseline at each input to record split-K reduction drift",
    )
    p.add_argument(
        "--max-nrmse",
        type=float,
        default=0.015,
        help="independent quantized-reference NRMSE limit for each implementation",
    )
    p.add_argument("--output", type=Path)
    args = p.parse_args(argv)
    if args.atom_module:
        if not args.checkpoint:
            p.error("--atom-module requires --checkpoint")
        args.atom_baseline = True
    if args.atom_profile == "stable-rne" and (not args.atom_baseline or args.atom_config_dir is None):
        p.error("--atom-profile stable-rne requires --atom-baseline/--atom-module and --atom-config-dir")
    if args.atom_config_dir is not None and args.atom_profile != "stable-rne":
        p.error("--atom-config-dir requires --atom-profile stable-rne")
    for seq in args.seq_lens:
        try:
            validate_shape(args.batch_size, seq)
        except ValueError as exc:
            p.error(str(exc))
    if not 0 <= args.layer <= 60:
        p.error("--layer must be in 0..60 for DSV4-Pro")
    if args.checkpoint:
        if args.shared_format != "fp8":
            p.error("native Pro checkpoint has an FP8 shared expert")
        expected = "hash" if args.layer < 3 else "bias"
        if args.routing not in ("auto", expected):
            p.error(f"checkpoint layer {args.layer} requires --routing {expected}")
    if args.atom_baseline and args.shared_format != "fp8":
        p.error("--atom-baseline requires the native --shared-format fp8")
    if not math.isfinite(args.max_nrmse) or not 0 < args.max_nrmse < 1:
        p.error("--max-nrmse must be finite and in (0,1)")
    for name in ("replays", "warmup", "repeats", "graph_iters", "atom_samples"):
        if getattr(args, name) < 1:
            p.error(f"--{name.replace('_', '-')} must be positive")
    return args


def error_metrics(actual, expected):
    import torch

    if not torch.isfinite(actual).all() or not torch.isfinite(expected).all():
        raise AssertionError("non-finite output")
    d, ref = actual.float() - expected.float(), expected.float()
    return {
        "max_abs": float(d.abs().max()),
        "rmse": float(d.square().mean().sqrt()),
        "nrmse": float(d.square().mean().sqrt() / ref.square().mean().sqrt().clamp_min(1e-12)),
    }


def bench_graph(fn, args, *, atom_collectives=False):
    from contextlib import nullcontext

    import torch

    for _ in range(args.warmup):
        fn()
    torch.cuda.synchronize()
    g = torch.cuda.CUDAGraph()
    if atom_collectives:
        from aiter.dist.parallel_state import graph_capture

        capture_context = graph_capture()
    else:
        capture_context = nullcontext()
    with capture_context as capture:
        # Standalone MoE may be called on the default stream. Let Torch pick
        # its non-default capture stream; ATOM collectives use their own one.
        capture_stream = capture.stream if atom_collectives else None
        with torch.cuda.graph(g, stream=capture_stream):
            for _ in range(args.graph_iters):
                fn()
    times = []
    for _ in range(args.repeats):
        start, end = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
        start.record()
        g.replay()
        end.record()
        end.synchronize()
        times.append(start.elapsed_time(end) * 1000 / args.graph_iters)
    return {"median_us": statistics.median(times), "min_us": min(times), "samples_us": times}


def main(argv=None):
    args = parse_args(argv)
    profile = None
    if args.atom_profile == "stable-rne":
        from .accuracy_config import configure

        profile = configure(args.atom_config_dir, args.tp)
    if args.atom_baseline:
        os.environ.setdefault("AITER_BF16_FP8_MOE_BOUND", "0")
        os.environ.setdefault("ATOM_MOE_GU_ITLV", "1")
    if args.atom_module:
        os.environ["ATOM_DSV4_MOE_MONOKERNEL"] = "1"
    import torch
    import torch.distributed as dist

    from ..moe import Dsv4MoeMonoKernel, PreparedMoeWeights
    from ..reference import moe_reference

    world = int(os.environ.get("WORLD_SIZE", "1"))
    if world != args.tp:
        raise ValueError(f"--tp {args.tp} requires torchrun WORLD_SIZE={args.tp}, got {world}")
    rank = int(os.environ.get("LOCAL_RANK", "0"))
    torch.cuda.set_device(rank)
    if world > 1:
        dist.init_process_group("nccl")
    cfg = Dsv4Config()
    h, inter, e = cfg.hidden, cfg.intermediate // world, cfg.experts + (args.shared_format == "fp4")
    device = torch.device("cuda", rank)
    tid2eid = None
    shared = None
    if args.checkpoint:
        from ..checkpoint import load_moe

        print(f"rank={rank}: loading layer={args.layer} from {args.checkpoint}", flush=True)
        cfg, weights, shared, tid2eid = load_moe(args.checkpoint, args.layer, world, rank, device)
        router, bias, up, us, down, ds = weights
    else:
        torch.manual_seed(args.seed)
        router = (torch.randn(cfg.experts, h, device=device) * 0.02).to(torch.bfloat16)
        bias = torch.randn(cfg.experts, device=device) * 0.1
        torch.manual_seed(args.seed + rank + 100)
        print(f"rank={rank}: preparing DSV4-Pro H={h} I={inter} E={e} TP={world}", flush=True)
        up = torch.randint(0, 256, (e, 2 * inter, h // 2), dtype=torch.uint8, device=device)
        down = torch.randint(0, 256, (e, h, inter // 2), dtype=torch.uint8, device=device)
        us = torch.randint(118, 122, (e, 2 * inter, h // 32), dtype=torch.uint8, device=device)
        ds = torch.randint(118, 122, (e, h, inter // 32), dtype=torch.uint8, device=device)
        if args.shared_format == "fp8":
            shared = (
                (torch.randn(2 * inter, h, device=device) * 30).to(torch.float8_e4m3fn),
                torch.full((2 * inter // 128, h // 128), 117, dtype=torch.uint8, device=device),
                (torch.randn(h, inter, device=device) * 30).to(torch.float8_e4m3fn),
                torch.full((h // 128, inter // 128), 117, dtype=torch.uint8, device=device),
            )
    prepared = PreparedMoeWeights(
        router, bias, up, us, down, ds, tp=world, config=cfg, shared=shared, hash_table=tid2eid
    )
    atom = None
    if args.atom_baseline:
        if args.atom_module:
            from ..atom_module import AtomMoeModule

            atom = AtomMoeModule(
                args.checkpoint, args.layer, (router, bias, up, us, down, ds), shared, tid2eid, world, rank
            )
        else:
            from ..atom_baseline import AtomMoeBaseline

            atom = AtomMoeBaseline((router, bias, up, us, down, ds), shared, cfg, tp=world)
        print(f"rank={rank}: ATOM selected activation dtype {atom.selected_dtype}", flush=True)
    results = []
    routing = args.routing
    if routing == "auto":
        routing = ("hash" if tid2eid is not None else "bias") if args.checkpoint else "both"
    modes = (False, True) if routing == "both" else (routing == "hash",)
    for seq in args.seq_lens:
        for hashed in modes:
            op = Dsv4MoeMonoKernel(prepared=prepared, seq_len=seq, config=cfg, tp=world, rank=rank, hash_routing=hashed)
            x = torch.empty(seq, h, dtype=torch.bfloat16, device=device)
            ids = torch.empty(seq, cfg.top_k, dtype=torch.int32, device=device) if hashed else None
            token_ids = torch.zeros(seq, dtype=torch.int64, device=device) if hashed and tid2eid is not None else None
            routing_args = {"token_ids": token_ids} if token_ids is not None else {"hash_ids": ids}
            out, staged = torch.empty_like(x), torch.empty_like(x)
            case = {
                "seq_len": seq,
                "batch_size": 1,
                "routing": "hash" if hashed else "bias",
                "checks": [],
                "passed": True,
            }
            print(f"rank={rank}: checking seq={seq} routing={case['routing']}", flush=True)
            # Capture first, then replay with different values at the same pointers.
            x.zero_()
            if ids is not None:
                ids.copy_(torch.arange(cfg.top_k, device=device).expand(seq, -1))
            op(x, **routing_args, out=out)
            op(x, **routing_args, out=staged, unfused=True)
            torch.cuda.synchronize()
            graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(graph):
                op(x, **routing_args, out=out)
            atom_args = {"token_ids": token_ids} if args.atom_module else {}
            if args.atom_module:
                atom(x, ids, **atom_args, mono=True)
                torch.cuda.synchronize()
                module_graph = torch.cuda.CUDAGraph()
                with torch.cuda.graph(module_graph):
                    module_out = atom(x, ids, **atom_args, mono=True)
            for replay in range(args.replays):
                torch.manual_seed(args.seed + replay + seq * 1000)
                x.copy_(torch.randn_like(x) * (0.2 if replay % 2 == 0 else 2.0))
                if ids is not None:
                    if tid2eid is not None:
                        token_ids.copy_(torch.randint(tid2eid.shape[0], (seq,), device=device))
                        ids.copy_(tid2eid[token_ids])
                    else:
                        ids.copy_(
                            torch.stack([torch.randperm(cfg.experts, device=device)[: cfg.top_k] for _ in range(seq)])
                        )
                graph.replay()
                op(x, **routing_args, out=staged, unfused=True)
                reference, expected_ids, expected_probs = moe_reference(
                    x, router, bias, up, us, down, ds, cfg, ids, shared
                )
                if world > 1:
                    parts = [torch.empty_like(reference) for _ in range(world)]
                    dist.all_gather(parts, reference)
                    reference = sum(p.float() for p in parts).to(torch.bfloat16)
                actual_ids, actual_probs = op.routing()
                torch.testing.assert_close(actual_ids, expected_ids, rtol=0, atol=0)
                torch.testing.assert_close(actual_probs, expected_probs, rtol=2e-5, atol=2e-6)
                torch.testing.assert_close(out, staged, rtol=0, atol=0)
                if args.atom_module:
                    module_graph.replay()
                    torch.testing.assert_close(module_out, out, rtol=0, atol=0)
                metrics = error_metrics(out, reference)
                case["passed"] &= metrics["nrmse"] <= args.max_nrmse
                case["checks"].append(metrics)
                if atom is not None:
                    # ATOM's BF16 split-K reductions can vary with execution
                    # order. Validate BOTH implementations against the same
                    # independent quantized oracle at the same fixed limit.
                    # Record direct disagreement and ATOM repeat drift rather
                    # than treating one nondeterministic sample as exact truth.
                    first_atom = None
                    comparisons = []
                    for _ in range(args.atom_samples):
                        actual_atom = atom(x, ids, **atom_args)
                        oracle_error = error_metrics(actual_atom, reference)
                        case["passed"] &= oracle_error["nrmse"] <= args.max_nrmse
                        if first_atom is None:
                            first_atom = actual_atom.clone()
                        comparisons.append(
                            {
                                "vs_oracle": oracle_error,
                                "mono_vs_atom": error_metrics(out, actual_atom),
                                "repeat_drift": error_metrics(actual_atom, first_atom),
                            }
                        )
                    case.setdefault("atom_checks", []).append(comparisons)
                print(f"rank={rank}: replay={replay} passed={case['passed']} {metrics}", flush=True)
            passed = torch.tensor(int(case["passed"]), device=device)
            if world > 1:
                dist.all_reduce(passed, op=dist.ReduceOp.MIN)
            case["all_ranks_passed"] = bool(passed.item())
            if args.bench and case["all_ranks_passed"]:
                # Both timed paths are GPU kernels with identical math, packing
                # and communication; Torch is solely the independent oracle.
                case["mono"] = bench_graph(lambda op=op: op(x, **routing_args, out=out), args)
                case["unfused"] = bench_graph(lambda op=op: op(x, **routing_args, out=staged, unfused=True), args)
                case["speedup"] = case["unfused"]["median_us"] / case["mono"]["median_us"]
                if atom is not None:
                    case["atom"] = bench_graph(
                        lambda: atom(x, ids, **atom_args), args, atom_collectives=args.atom_module
                    )
                    case["speedup_vs_atom"] = case["atom"]["median_us"] / case["mono"]["median_us"]
            results.append(case)
            op.close()
            del op
    result = {
        "model": "DSV4-Pro",
        "component": "moe",
        "tp": world,
        "rank": rank,
        "seed": args.seed,
        "checkpoint": str(args.checkpoint) if args.checkpoint else None,
        "atom_baseline_kind": "module" if args.atom_module else "operations" if atom is not None else None,
        "atom_profile": args.atom_profile if atom is not None else None,
        "atom_profile_manifest": profile,
        "bf16_gemm_config_override": os.environ.get("AITER_CONFIG_GEMM_BF16"),
        "shared_gemm_config_override": os.environ.get("AITER_CONFIG_GEMM_A8W8_BLOCKSCALE_BPRESHUFFLE"),
        "routed_mid_contract": "FP32 SwiGLU directly to per32 FP8, native fused exponent",
        "layer": args.layer if args.checkpoint else None,
        "shared_format": args.shared_format,
        "validation": {
            "max_nrmse_vs_independent_reference": args.max_nrmse,
            "mono_vs_unfused": "bitwise",
            "routing_ids": "exact",
            "routing_probs_rtol": 2e-5,
            "routing_probs_atol": 2e-6,
            "atom_samples": args.atom_samples if atom is not None else 0,
        },
        "mono_launches": 1,
        "unfused_launches": 5,
        "cases": results,
    }
    if world > 1:
        ranks = [None] * world
        dist.all_gather_object(ranks, results)
        if rank == 0:
            summary = []
            for i, case in enumerate(results):
                row = {
                    "seq_len": case["seq_len"],
                    "routing": case["routing"],
                    "max_nrmse": max(c["nrmse"] for r in ranks for c in r[i]["checks"]),
                }
                if "mono" in case:
                    for name in ("mono", "unfused", "atom"):
                        if name in case:
                            row[name + "_slowest_rank_median_us"] = max(r[i][name]["median_us"] for r in ranks)
                    row["speedup"] = row["unfused_slowest_rank_median_us"] / row["mono_slowest_rank_median_us"]
                    if atom is not None:
                        row["speedup_vs_atom"] = row["atom_slowest_rank_median_us"] / row["mono_slowest_rank_median_us"]
                summary.append(row)
            result["tp_summary"] = summary
    if args.output:
        path = (
            args.output if world == 1 else args.output.with_name(f"{args.output.stem}.rank{rank}{args.output.suffix}")
        )
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2), flush=True)
    if args.atom_module:
        atom.close()
    if dist.is_initialized():
        dist.destroy_process_group()
    if not all(c["all_ranks_passed"] for c in results):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
