
# Autogenerated by mlir-tblgen; don't manually edit.

from enum import IntEnum, auto, IntFlag
from ._ods_common import _cext as _ods_cext
from ..ir import register_attribute_builder
_ods_ir = _ods_cext.ir

class AddressSpace(IntEnum):
    """allowed 32-bit signless integer cases: 0, 1, 2"""

    Global = 0
    Shared = 1
    Register = 2

    def __str__(self):
        if self is AddressSpace.Global:
            return "global"
        if self is AddressSpace.Shared:
            return "shared"
        if self is AddressSpace.Register:
            return "register"
        raise ValueError("Unknown AddressSpace enum entry.")



@register_attribute_builder("Fly_AddressSpace")
def _fly_addressspace(x, context):
    return _ods_ir.IntegerAttr.get(_ods_ir.IntegerType.get_signless(32, context=context), int(x))

class CachePolicy(IntEnum):
    """allowed 32-bit signless integer cases: 0, 1"""

    CacheGlobal = 0
    CacheAlways = 1

    def __str__(self):
        if self is CachePolicy.CacheGlobal:
            return "cache_global"
        if self is CachePolicy.CacheAlways:
            return "cache_always"
        raise ValueError("Unknown CachePolicy enum entry.")



@register_attribute_builder("Fly_CachePolicy")
def _fly_cachepolicy(x, context):
    return _ods_ir.IntegerAttr.get(_ods_ir.IntegerType.get_signless(32, context=context), int(x))

@register_attribute_builder("Fly_AddressSpaceAttr")
def _fly_addressspaceattr(x, context):
    return _ods_ir.Attribute.parse(f'#fly<address_space {str(x)}>', context=context)

@register_attribute_builder("Fly_CachePolicyAttr")
def _fly_cachepolicyattr(x, context):
    return _ods_ir.Attribute.parse(f'#fly<cache_policy {str(x)}>', context=context)

