
# Autogenerated by mlir-tblgen; don't manually edit.

from enum import IntEnum, auto, IntFlag
from flydsl._mlir.dialects._ods_common import _cext as _ods_cext
from flydsl._mlir.ir import register_attribute_builder
_ods_ir = _ods_cext.ir

class BufferOOBMode(IntEnum):
    """ROCDL buffer out-of-bounds mode"""

    Any = 0
    Relaxed = 1
    Strict = 2

    def __str__(self):
        if self is BufferOOBMode.Any:
            return "any"
        if self is BufferOOBMode.Relaxed:
            return "relaxed"
        if self is BufferOOBMode.Strict:
            return "strict"
        raise ValueError("Unknown BufferOOBMode enum entry.")



class Gfx12AtomicCachePolicy(IntFlag):
    """gfx12 atomic cache policy bits"""

    none = 0
    keep_return = 1
    nt = 2
    cascade = 4
    scope_se = 8
    scope_dev = 16
    scope_sys = 24
    nv = 32
    volatile_op = 2147483648

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is Gfx12AtomicCachePolicy.none:
            return "none"
        if self is Gfx12AtomicCachePolicy.keep_return:
            return "return"
        if self is Gfx12AtomicCachePolicy.nt:
            return "nt"
        if self is Gfx12AtomicCachePolicy.cascade:
            return "cascade"
        if self is Gfx12AtomicCachePolicy.scope_se:
            return "scope_se"
        if self is Gfx12AtomicCachePolicy.scope_dev:
            return "scope_dev"
        if self is Gfx12AtomicCachePolicy.scope_sys:
            return "scope_sys"
        if self is Gfx12AtomicCachePolicy.nv:
            return "nv"
        if self is Gfx12AtomicCachePolicy.volatile_op:
            return "volatile"
        raise ValueError("Unknown Gfx12AtomicCachePolicy enum entry.")



class Gfx12CachePolicy(IntFlag):
    """gfx12 cache policy bits"""

    none = 0
    nt = 1
    ht = 2
    lu = 3
    nt_rt = 4
    rt_nt = 5
    nt_ht = 6
    nt_wb = 7
    scope_se = 8
    scope_dev = 16
    scope_sys = 24
    nv = 32
    swz = 64
    scal = 2048
    volatile_op = 2147483648

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is Gfx12CachePolicy.none:
            return "none"
        if self is Gfx12CachePolicy.nt:
            return "nt"
        if self is Gfx12CachePolicy.ht:
            return "ht"
        if self is Gfx12CachePolicy.lu:
            return "lu"
        if self is Gfx12CachePolicy.nt_rt:
            return "nt_rt"
        if self is Gfx12CachePolicy.rt_nt:
            return "rt_nt"
        if self is Gfx12CachePolicy.nt_ht:
            return "nt_ht"
        if self is Gfx12CachePolicy.nt_wb:
            return "nt_wb"
        if self is Gfx12CachePolicy.scope_se:
            return "scope_se"
        if self is Gfx12CachePolicy.scope_dev:
            return "scope_dev"
        if self is Gfx12CachePolicy.scope_sys:
            return "scope_sys"
        if self is Gfx12CachePolicy.nv:
            return "nv"
        if self is Gfx12CachePolicy.swz:
            return "swz"
        if self is Gfx12CachePolicy.scal:
            return "scal"
        if self is Gfx12CachePolicy.volatile_op:
            return "volatile"
        raise ValueError("Unknown Gfx12CachePolicy enum entry.")



class Gfx942CachePolicy(IntFlag):
    """gfx942 buffer cache policy bits"""

    none = 0
    sc0 = 1
    nt = 2
    swz = 8
    sc1 = 16
    volatile_op = 2147483648

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is Gfx942CachePolicy.none:
            return "none"
        if self is Gfx942CachePolicy.sc0:
            return "sc0"
        if self is Gfx942CachePolicy.nt:
            return "nt"
        if self is Gfx942CachePolicy.swz:
            return "swz"
        if self is Gfx942CachePolicy.sc1:
            return "sc1"
        if self is Gfx942CachePolicy.volatile_op:
            return "volatile"
        raise ValueError("Unknown Gfx942CachePolicy enum entry.")



class MFMANegModifier(IntFlag):
    """negation modifier bitfield for gfx94x double-precision MFMA"""

    none = 0
    neg_a = 1
    neg_b = 2
    neg_c = 4

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is MFMANegModifier.none:
            return "none"
        if self is MFMANegModifier.neg_a:
            return "neg_a"
        if self is MFMANegModifier.neg_b:
            return "neg_b"
        if self is MFMANegModifier.neg_c:
            return "neg_c"
        raise ValueError("Unknown MFMANegModifier enum entry.")



class MFMAPermB(IntEnum):
    """permutations of the lanes storing B in an MFMA"""

    none = 0
    bcast_first_32 = 1
    bcast_second_32 = 2
    rotate_16_right = 3
    bcast_first_16 = 4
    bcast_second_16 = 5
    bcast_third_16 = 6
    bcast_fourth_16 = 7

    def __str__(self):
        if self is MFMAPermB.none:
            return "none"
        if self is MFMAPermB.bcast_first_32:
            return "bcast_first_32"
        if self is MFMAPermB.bcast_second_32:
            return "bcast_second_32"
        if self is MFMAPermB.rotate_16_right:
            return "rotate_16_right"
        if self is MFMAPermB.bcast_first_16:
            return "bcast_first_16"
        if self is MFMAPermB.bcast_second_16:
            return "bcast_second_16"
        if self is MFMAPermB.bcast_third_16:
            return "bcast_third_16"
        if self is MFMAPermB.bcast_fourth_16:
            return "bcast_fourth_16"
        raise ValueError("Unknown MFMAPermB enum entry.")



class MatrixFormat(IntEnum):
    """matrix operand formats selected by scaled MFMA/WMMA format fields"""

    fp8_e4m3 = 0
    fp8_e5m2 = 1
    fp6_e2m3 = 2
    fp6_e3m2 = 3
    fp4_e2m1 = 4

    def __str__(self):
        if self is MatrixFormat.fp8_e4m3:
            return "fp8_e4m3"
        if self is MatrixFormat.fp8_e5m2:
            return "fp8_e5m2"
        if self is MatrixFormat.fp6_e2m3:
            return "fp6_e2m3"
        if self is MatrixFormat.fp6_e3m2:
            return "fp6_e3m2"
        if self is MatrixFormat.fp4_e2m1:
            return "fp4_e2m1"
        raise ValueError("Unknown MatrixFormat enum entry.")



class PreGfx12CachePolicy(IntFlag):
    """pre-gfx12 buffer cache policy bits"""

    none = 0
    glc = 1
    slc = 2
    dlc = 4
    swz = 8
    scc = 16
    all = 23
    volatile_op = 2147483648

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is PreGfx12CachePolicy.none:
            return "none"
        if self is PreGfx12CachePolicy.glc:
            return "glc"
        if self is PreGfx12CachePolicy.slc:
            return "slc"
        if self is PreGfx12CachePolicy.dlc:
            return "dlc"
        if self is PreGfx12CachePolicy.swz:
            return "swz"
        if self is PreGfx12CachePolicy.scc:
            return "scc"
        if self is PreGfx12CachePolicy.all:
            return "all"
        if self is PreGfx12CachePolicy.volatile_op:
            return "volatile"
        raise ValueError("Unknown PreGfx12CachePolicy enum entry.")



class SchedGroupMask(IntFlag):
    """instruction type mask for scheduling barriers"""

    none = 0
    non_mem_non_sideeffect = 1
    valu = 2
    salu = 4
    mfma_wmma = 8
    all_vmem = 16
    vmem_read = 32
    vmem_write = 64
    all_ds = 128
    ds_read = 256
    ds_write = 512
    transcendental = 1024
    ldsdma = 2048
    all = 4095

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is SchedGroupMask.none:
            return "none"
        if self is SchedGroupMask.non_mem_non_sideeffect:
            return "non_mem_non_sideeffect"
        if self is SchedGroupMask.valu:
            return "valu"
        if self is SchedGroupMask.salu:
            return "salu"
        if self is SchedGroupMask.mfma_wmma:
            return "mfma_wmma"
        if self is SchedGroupMask.all_vmem:
            return "all_vmem"
        if self is SchedGroupMask.vmem_read:
            return "vmem_read"
        if self is SchedGroupMask.vmem_write:
            return "vmem_write"
        if self is SchedGroupMask.all_ds:
            return "all_ds"
        if self is SchedGroupMask.ds_read:
            return "ds_read"
        if self is SchedGroupMask.ds_write:
            return "ds_write"
        if self is SchedGroupMask.transcendental:
            return "transcendental"
        if self is SchedGroupMask.ldsdma:
            return "ldsdma"
        if self is SchedGroupMask.all:
            return "all"
        raise ValueError("Unknown SchedGroupMask enum entry.")



class WMMACModifier(IntFlag):
    """WMMA C operand modifiers"""

    none = 0
    neg = 1
    abs = 2
    neg_abs = 3

    def __iter__(self):
        return iter([case for case in type(self) if (self & case) is case and self is not case])
    def __len__(self):
        return bin(self).count("1")

    def __str__(self):
        if len(self) > 1:
            return "|".join(map(str, self))
        if self is WMMACModifier.none:
            return "none"
        if self is WMMACModifier.neg:
            return "neg"
        if self is WMMACModifier.abs:
            return "abs"
        if self is WMMACModifier.neg_abs:
            return "neg_abs"
        raise ValueError("Unknown WMMACModifier enum entry.")



class WMMAMatrixScale(IntEnum):
    """matrix scale row selector"""

    row0 = 0
    row1 = 1

    def __str__(self):
        if self is WMMAMatrixScale.row0:
            return "row0"
        if self is WMMAMatrixScale.row1:
            return "row1"
        raise ValueError("Unknown WMMAMatrixScale enum entry.")



class WMMAMatrixScaleFormat(IntEnum):
    """matrix scale exponent formats"""

    e8 = 0
    e5m3 = 1
    e4m3 = 2

    def __str__(self):
        if self is WMMAMatrixScaleFormat.e8:
            return "e8"
        if self is WMMAMatrixScaleFormat.e5m3:
            return "e5m3"
        if self is WMMAMatrixScaleFormat.e4m3:
            return "e4m3"
        raise ValueError("Unknown WMMAMatrixScaleFormat enum entry.")



@register_attribute_builder("rocdl.ROCDL_BufferOOBModeAttr")
def _rocdl_bufferoobmodeattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl.buffer_oob_mode<{str(x)}>', context=context)

@register_attribute_builder("rocdl.ROCDL_Gfx12AtomicCachePolicyAttr")
def _rocdl_gfx12atomiccachepolicyattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<gfx12_atomic_cache_policy {str(Gfx12AtomicCachePolicy(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_Gfx12CachePolicyAttr")
def _rocdl_gfx12cachepolicyattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<gfx12_cache_policy {str(Gfx12CachePolicy(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_Gfx942CachePolicyAttr")
def _rocdl_gfx942cachepolicyattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<gfx942_cache_policy {str(Gfx942CachePolicy(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_MFMANegModifierAttr")
def _rocdl_mfmanegmodifierattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<mfma_neg_modifier {str(MFMANegModifier(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_MFMAPermBAttr")
def _rocdl_mfmapermbattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<mfma_perm_b {str(MFMAPermB(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_MatrixFormatAttr")
def _rocdl_matrixformatattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<matrix_format {str(MatrixFormat(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_PreGfx12CachePolicyAttr")
def _rocdl_pregfx12cachepolicyattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<pre_gfx12_cache_policy {str(PreGfx12CachePolicy(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_SchedGroupMaskAttr")
def _rocdl_schedgroupmaskattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<sched_group_mask {str(SchedGroupMask(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_WMMACModifierAttr")
def _rocdl_wmmacmodifierattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<wmma_c_modifier {str(WMMACModifier(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_WMMAMatrixScaleAttr")
def _rocdl_wmmamatrixscaleattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<wmma_matrix_scale {str(WMMAMatrixScale(x))}>', context=context)

@register_attribute_builder("rocdl.ROCDL_WMMAMatrixScaleFormatAttr")
def _rocdl_wmmamatrixscaleformatattr(x, context):
    return _ods_ir.Attribute.parse(f'#rocdl<wmma_matrix_scale_format {str(WMMAMatrixScaleFormat(x))}>', context=context)

