# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 FlyDSL Project Contributors
"""Generate ``kernels/moe/moe_2stage_a16wmix/a16wmix_tuned.csv`` FROM the current
default-path (``use_csv_config=False``) tile heuristics.

The CSV is a *data* snapshot of the code heuristics: for every tuned (w_dtype,
shape, token) cell it records the exact tile geometry that the old inline
heuristics would have resolved, per stage (gemm1/gemm2). It is regenerated by
this script so it is never hand-authored -- run it after any deliberate re-tune.

This module deliberately re-implements the *old* heuristic here (not importing
the shipped resolver) so the equivalence check has an independent oracle.
"""

import csv
import os

# ---------------------------------------------------------------------------
# The OLD default-path heuristics, transcribed verbatim from the pre-refactor
# flydsl_a16w4_gemm1 / flydsl_a16w4_gemm2 (use_csv_config=False branch).
# ---------------------------------------------------------------------------


def _default_tile_n(N, *, w_dtype="mxfp4"):
    if w_dtype == "int4":
        if N % 128 == 0:
            return 128
        return 64 if N % 64 == 0 else 128
    return 256 if N % 256 == 0 else 128


def a16wi4_recommend_block_m(tokens, experts, topk, *, base_block_m=32):
    if int(base_block_m) != 32 or int(experts) <= 0:
        return int(base_block_m)
    routes = int(tokens) * int(topk)
    m_blocks_32 = -(-routes // (int(experts) * 32))
    return 64 if m_blocks_32 == 2 else int(base_block_m)


def old_gemm1_tiles(*, D_HIDDEN, D_INTER, n_tokens, w_dtype, tile_m):
    """Reproduce the old gemm1 default-path resolution (all tile args at defaults:
    tile_n=None, tile_k=256, k_wave=1, xcd_swizzle=0, waves_per_eu=None, b_nt=None).

    ``tile_m`` (BM) is caller-supplied. For int4 the caller is expected to pass the
    a16wi4_recommend_block_m value; the BM==64 gate below then keys off it.
    """
    BM = int(tile_m)
    TILE_K = 256
    k_wave = 1
    xcd_swizzle = 0
    _m = int(n_tokens)
    b_cache_mod = 2 if (16 <= _m <= 1024) else 0

    if w_dtype == "mxfp4" and _m >= 16 and D_HIDDEN % 128 == 0:
        TILE_K = 128
        xcd_swizzle = 1

    # TILE_N is None on the default path -> resolve.
    if w_dtype == "mxfp4" and _m <= 2 and D_INTER % 64 == 0:
        TILE_N = 64
        if D_HIDDEN % 512 == 0:
            TILE_K = 128
            k_wave = 4
    elif w_dtype == "int4" and BM == 64 and D_INTER % 64 == 0:
        TILE_N = 64
    elif w_dtype == "mxfp4" and D_INTER % 128 == 0:
        TILE_N = 128
    else:
        TILE_N = _default_tile_n(D_INTER, w_dtype=w_dtype)

    return {
        "tile_m": BM,
        "tile_n": TILE_N,
        "tile_k": TILE_K,
        "k_wave": k_wave,
        "xcd_swizzle": xcd_swizzle,
        "b_nt": b_cache_mod,
    }


def old_gemm2_tiles(*, D_HIDDEN, D_INTER, M_logical, w_dtype, tile_m):
    """Reproduce the old gemm2 default-path resolution (tile_n=256, tile_k=256,
    xcd_swizzle=1, b_nt=None). gemm2 has no k_wave (fixed 4-wave N-split)."""
    BM = int(tile_m)
    TILE_N = 256
    TILE_K = 256
    xcd_swizzle = 1
    _m = int(M_logical)
    b_cache_mod = 0 if (_m <= 16 or _m >= 2048) else 2
    return {
        "tile_m": BM,
        "tile_n": TILE_N,
        "tile_k": TILE_K,
        "k_wave": 1,  # gemm2 has no slice-K
        "xcd_swizzle": xcd_swizzle,
        "b_nt": b_cache_mod,
    }


# ---------------------------------------------------------------------------
# Tuned shape catalog and token sweep.
# ---------------------------------------------------------------------------

TOKENS = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]

# (w_dtype, model_dim, inter_dim, experts, topk). Base tile_m per shape family:
# mxfp4/bf16 use BM=32 (the atomic-gemm2 mid-band default the e2e tests pass);
# int4 uses the a16wi4_recommend_block_m value (32 or 64 at the fill point).
SHAPES = [
    # a16w4 (mxfp4): Kimi-K3, E896 k16.
    ("mxfp4", 3584, 384, 896, 16),
    ("mxfp4", 3584, 512, 896, 16),
    # a16wi4 (int4): 7168 x {256,512,1024}, E384/k8 + E385/k9.
    ("int4", 7168, 256, 384, 8),
    ("int4", 7168, 512, 384, 8),
    ("int4", 7168, 1024, 384, 8),
    ("int4", 7168, 256, 385, 9),
    ("int4", 7168, 512, 385, 9),
    ("int4", 7168, 1024, 385, 9),
    # a16w16 (bf16): the shapes it is tested on (kimi + small e2e).
    ("bf16", 3584, 512, 896, 16),
    ("bf16", 1024, 256, 8, 2),
]

FIELDS = [
    "w_dtype",
    "model_dim",
    "inter_dim",
    "experts",
    "topk",
    "token",
    "stage",
    "tile_m",
    "tile_n",
    "tile_k",
    "k_wave",
    "xcd_swizzle",
    "b_nt",
]


def base_tile_m(w_dtype, tokens, experts, topk):
    """Per-cell base BM used to seed the heuristic (mirrors the caller convention):
    int4 -> a16wi4_recommend_block_m; mxfp4/bf16 -> 32 (atomic-gemm2 default)."""
    if w_dtype == "int4":
        return a16wi4_recommend_block_m(tokens, experts, topk)
    return 32


def gen_rows():
    rows = []
    for w_dtype, md, inter, E, topk in SHAPES:
        for tok in TOKENS:
            bm = base_tile_m(w_dtype, tok, E, topk)
            g1 = old_gemm1_tiles(D_HIDDEN=md, D_INTER=inter, n_tokens=tok, w_dtype=w_dtype, tile_m=bm)
            g2 = old_gemm2_tiles(D_HIDDEN=md, D_INTER=inter, M_logical=tok, w_dtype=w_dtype, tile_m=bm)
            for stage, cfg in ((1, g1), (2, g2)):
                rows.append(
                    {
                        "w_dtype": w_dtype,
                        "model_dim": md,
                        "inter_dim": inter,
                        "experts": E,
                        "topk": topk,
                        "token": tok,
                        "stage": stage,
                        "tile_m": cfg["tile_m"],
                        "tile_n": cfg["tile_n"],
                        "tile_k": cfg["tile_k"],
                        "k_wave": cfg["k_wave"],
                        "xcd_swizzle": cfg["xcd_swizzle"],
                        "b_nt": cfg["b_nt"],
                    }
                )
    return rows


def main():
    out = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "kernels",
        "moe",
        "moe_2stage_a16wmix",
        "a16wmix_tuned.csv",
    )
    rows = gen_rows()
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {len(rows)} rows -> {out}")


if __name__ == "__main__":
    main()
